/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum AlertType implements org.apache.avro.generic.GenericEnumSymbol<AlertType> {
  THRESHOLD_EXCEEDED, THRESHOLD_RECOVERED, ANOMALY_DETECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertType\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"THRESHOLD_EXCEEDED\",\"THRESHOLD_RECOVERED\",\"ANOMALY_DETECTED\"],\"default\":\"THRESHOLD_EXCEEDED\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
