/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired when application shuts down */
@org.apache.avro.specific.AvroGenerated
public class ApplicationShutdown extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6508053089434162318L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationShutdown\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired when application shuts down\",\"fields\":[{\"name\":\"shutdown_reason\",\"type\":{\"type\":\"enum\",\"name\":\"ShutdownReason\",\"symbols\":[\"GRACEFUL\",\"FORCED\",\"ERROR\",\"SIGNAL\",\"OUT_OF_MEMORY\",\"EXTERNAL_REQUEST\"],\"default\":\"GRACEFUL\"},\"doc\":\"Reason for application shutdown\"},{\"name\":\"uptime_seconds\",\"type\":\"long\",\"doc\":\"Total application uptime in seconds\"},{\"name\":\"final_memory_usage_mb\",\"type\":[\"null\",\"long\"],\"doc\":\"Memory usage at shutdown in MB\",\"default\":null},{\"name\":\"cleanup_time_ms\",\"type\":[\"null\",\"long\"],\"doc\":\"Time spent on cleanup operations in milliseconds\",\"default\":null},{\"name\":\"exit_code\",\"type\":\"int\",\"doc\":\"Application exit code\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ApplicationShutdown> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ApplicationShutdown> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ApplicationShutdown> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ApplicationShutdown> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ApplicationShutdown> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ApplicationShutdown to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ApplicationShutdown from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ApplicationShutdown instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ApplicationShutdown fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Reason for application shutdown */
  private com.tbw.security.securityevents.ShutdownReason shutdown_reason;
  /** Total application uptime in seconds */
  private long uptime_seconds;
  /** Memory usage at shutdown in MB */
  private java.lang.Long final_memory_usage_mb;
  /** Time spent on cleanup operations in milliseconds */
  private java.lang.Long cleanup_time_ms;
  /** Application exit code */
  private int exit_code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationShutdown() {}

  /**
   * All-args constructor.
   * @param shutdown_reason Reason for application shutdown
   * @param uptime_seconds Total application uptime in seconds
   * @param final_memory_usage_mb Memory usage at shutdown in MB
   * @param cleanup_time_ms Time spent on cleanup operations in milliseconds
   * @param exit_code Application exit code
   */
  public ApplicationShutdown(com.tbw.security.securityevents.ShutdownReason shutdown_reason, java.lang.Long uptime_seconds, java.lang.Long final_memory_usage_mb, java.lang.Long cleanup_time_ms, java.lang.Integer exit_code) {
    this.shutdown_reason = shutdown_reason;
    this.uptime_seconds = uptime_seconds;
    this.final_memory_usage_mb = final_memory_usage_mb;
    this.cleanup_time_ms = cleanup_time_ms;
    this.exit_code = exit_code;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shutdown_reason;
    case 1: return uptime_seconds;
    case 2: return final_memory_usage_mb;
    case 3: return cleanup_time_ms;
    case 4: return exit_code;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shutdown_reason = (com.tbw.security.securityevents.ShutdownReason)value$; break;
    case 1: uptime_seconds = (java.lang.Long)value$; break;
    case 2: final_memory_usage_mb = (java.lang.Long)value$; break;
    case 3: cleanup_time_ms = (java.lang.Long)value$; break;
    case 4: exit_code = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'shutdown_reason' field.
   * @return Reason for application shutdown
   */
  public com.tbw.security.securityevents.ShutdownReason getShutdownReason() {
    return shutdown_reason;
  }


  /**
   * Sets the value of the 'shutdown_reason' field.
   * Reason for application shutdown
   * @param value the value to set.
   */
  public void setShutdownReason(com.tbw.security.securityevents.ShutdownReason value) {
    this.shutdown_reason = value;
  }

  /**
   * Gets the value of the 'uptime_seconds' field.
   * @return Total application uptime in seconds
   */
  public long getUptimeSeconds() {
    return uptime_seconds;
  }


  /**
   * Sets the value of the 'uptime_seconds' field.
   * Total application uptime in seconds
   * @param value the value to set.
   */
  public void setUptimeSeconds(long value) {
    this.uptime_seconds = value;
  }

  /**
   * Gets the value of the 'final_memory_usage_mb' field.
   * @return Memory usage at shutdown in MB
   */
  public java.lang.Long getFinalMemoryUsageMb() {
    return final_memory_usage_mb;
  }


  /**
   * Sets the value of the 'final_memory_usage_mb' field.
   * Memory usage at shutdown in MB
   * @param value the value to set.
   */
  public void setFinalMemoryUsageMb(java.lang.Long value) {
    this.final_memory_usage_mb = value;
  }

  /**
   * Gets the value of the 'cleanup_time_ms' field.
   * @return Time spent on cleanup operations in milliseconds
   */
  public java.lang.Long getCleanupTimeMs() {
    return cleanup_time_ms;
  }


  /**
   * Sets the value of the 'cleanup_time_ms' field.
   * Time spent on cleanup operations in milliseconds
   * @param value the value to set.
   */
  public void setCleanupTimeMs(java.lang.Long value) {
    this.cleanup_time_ms = value;
  }

  /**
   * Gets the value of the 'exit_code' field.
   * @return Application exit code
   */
  public int getExitCode() {
    return exit_code;
  }


  /**
   * Sets the value of the 'exit_code' field.
   * Application exit code
   * @param value the value to set.
   */
  public void setExitCode(int value) {
    this.exit_code = value;
  }

  /**
   * Creates a new ApplicationShutdown RecordBuilder.
   * @return A new ApplicationShutdown RecordBuilder
   */
  public static com.tbw.security.securityevents.ApplicationShutdown.Builder newBuilder() {
    return new com.tbw.security.securityevents.ApplicationShutdown.Builder();
  }

  /**
   * Creates a new ApplicationShutdown RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationShutdown RecordBuilder
   */
  public static com.tbw.security.securityevents.ApplicationShutdown.Builder newBuilder(com.tbw.security.securityevents.ApplicationShutdown.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ApplicationShutdown.Builder();
    } else {
      return new com.tbw.security.securityevents.ApplicationShutdown.Builder(other);
    }
  }

  /**
   * Creates a new ApplicationShutdown RecordBuilder by copying an existing ApplicationShutdown instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationShutdown RecordBuilder
   */
  public static com.tbw.security.securityevents.ApplicationShutdown.Builder newBuilder(com.tbw.security.securityevents.ApplicationShutdown other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ApplicationShutdown.Builder();
    } else {
      return new com.tbw.security.securityevents.ApplicationShutdown.Builder(other);
    }
  }

  /**
   * RecordBuilder for ApplicationShutdown instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationShutdown>
    implements org.apache.avro.data.RecordBuilder<ApplicationShutdown> {

    /** Reason for application shutdown */
    private com.tbw.security.securityevents.ShutdownReason shutdown_reason;
    /** Total application uptime in seconds */
    private long uptime_seconds;
    /** Memory usage at shutdown in MB */
    private java.lang.Long final_memory_usage_mb;
    /** Time spent on cleanup operations in milliseconds */
    private java.lang.Long cleanup_time_ms;
    /** Application exit code */
    private int exit_code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.ApplicationShutdown.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shutdown_reason)) {
        this.shutdown_reason = data().deepCopy(fields()[0].schema(), other.shutdown_reason);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.uptime_seconds)) {
        this.uptime_seconds = data().deepCopy(fields()[1].schema(), other.uptime_seconds);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.final_memory_usage_mb)) {
        this.final_memory_usage_mb = data().deepCopy(fields()[2].schema(), other.final_memory_usage_mb);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.cleanup_time_ms)) {
        this.cleanup_time_ms = data().deepCopy(fields()[3].schema(), other.cleanup_time_ms);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.exit_code)) {
        this.exit_code = data().deepCopy(fields()[4].schema(), other.exit_code);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationShutdown instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.ApplicationShutdown other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.shutdown_reason)) {
        this.shutdown_reason = data().deepCopy(fields()[0].schema(), other.shutdown_reason);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uptime_seconds)) {
        this.uptime_seconds = data().deepCopy(fields()[1].schema(), other.uptime_seconds);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.final_memory_usage_mb)) {
        this.final_memory_usage_mb = data().deepCopy(fields()[2].schema(), other.final_memory_usage_mb);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cleanup_time_ms)) {
        this.cleanup_time_ms = data().deepCopy(fields()[3].schema(), other.cleanup_time_ms);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.exit_code)) {
        this.exit_code = data().deepCopy(fields()[4].schema(), other.exit_code);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'shutdown_reason' field.
      * Reason for application shutdown
      * @return The value.
      */
    public com.tbw.security.securityevents.ShutdownReason getShutdownReason() {
      return shutdown_reason;
    }


    /**
      * Sets the value of the 'shutdown_reason' field.
      * Reason for application shutdown
      * @param value The value of 'shutdown_reason'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder setShutdownReason(com.tbw.security.securityevents.ShutdownReason value) {
      validate(fields()[0], value);
      this.shutdown_reason = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'shutdown_reason' field has been set.
      * Reason for application shutdown
      * @return True if the 'shutdown_reason' field has been set, false otherwise.
      */
    public boolean hasShutdownReason() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'shutdown_reason' field.
      * Reason for application shutdown
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder clearShutdownReason() {
      shutdown_reason = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'uptime_seconds' field.
      * Total application uptime in seconds
      * @return The value.
      */
    public long getUptimeSeconds() {
      return uptime_seconds;
    }


    /**
      * Sets the value of the 'uptime_seconds' field.
      * Total application uptime in seconds
      * @param value The value of 'uptime_seconds'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder setUptimeSeconds(long value) {
      validate(fields()[1], value);
      this.uptime_seconds = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'uptime_seconds' field has been set.
      * Total application uptime in seconds
      * @return True if the 'uptime_seconds' field has been set, false otherwise.
      */
    public boolean hasUptimeSeconds() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'uptime_seconds' field.
      * Total application uptime in seconds
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder clearUptimeSeconds() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'final_memory_usage_mb' field.
      * Memory usage at shutdown in MB
      * @return The value.
      */
    public java.lang.Long getFinalMemoryUsageMb() {
      return final_memory_usage_mb;
    }


    /**
      * Sets the value of the 'final_memory_usage_mb' field.
      * Memory usage at shutdown in MB
      * @param value The value of 'final_memory_usage_mb'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder setFinalMemoryUsageMb(java.lang.Long value) {
      validate(fields()[2], value);
      this.final_memory_usage_mb = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'final_memory_usage_mb' field has been set.
      * Memory usage at shutdown in MB
      * @return True if the 'final_memory_usage_mb' field has been set, false otherwise.
      */
    public boolean hasFinalMemoryUsageMb() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'final_memory_usage_mb' field.
      * Memory usage at shutdown in MB
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder clearFinalMemoryUsageMb() {
      final_memory_usage_mb = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'cleanup_time_ms' field.
      * Time spent on cleanup operations in milliseconds
      * @return The value.
      */
    public java.lang.Long getCleanupTimeMs() {
      return cleanup_time_ms;
    }


    /**
      * Sets the value of the 'cleanup_time_ms' field.
      * Time spent on cleanup operations in milliseconds
      * @param value The value of 'cleanup_time_ms'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder setCleanupTimeMs(java.lang.Long value) {
      validate(fields()[3], value);
      this.cleanup_time_ms = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'cleanup_time_ms' field has been set.
      * Time spent on cleanup operations in milliseconds
      * @return True if the 'cleanup_time_ms' field has been set, false otherwise.
      */
    public boolean hasCleanupTimeMs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'cleanup_time_ms' field.
      * Time spent on cleanup operations in milliseconds
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder clearCleanupTimeMs() {
      cleanup_time_ms = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'exit_code' field.
      * Application exit code
      * @return The value.
      */
    public int getExitCode() {
      return exit_code;
    }


    /**
      * Sets the value of the 'exit_code' field.
      * Application exit code
      * @param value The value of 'exit_code'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder setExitCode(int value) {
      validate(fields()[4], value);
      this.exit_code = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'exit_code' field has been set.
      * Application exit code
      * @return True if the 'exit_code' field has been set, false otherwise.
      */
    public boolean hasExitCode() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'exit_code' field.
      * Application exit code
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationShutdown.Builder clearExitCode() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ApplicationShutdown build() {
      try {
        ApplicationShutdown record = new ApplicationShutdown();
        record.shutdown_reason = fieldSetFlags()[0] ? this.shutdown_reason : (com.tbw.security.securityevents.ShutdownReason) defaultValue(fields()[0]);
        record.uptime_seconds = fieldSetFlags()[1] ? this.uptime_seconds : (java.lang.Long) defaultValue(fields()[1]);
        record.final_memory_usage_mb = fieldSetFlags()[2] ? this.final_memory_usage_mb : (java.lang.Long) defaultValue(fields()[2]);
        record.cleanup_time_ms = fieldSetFlags()[3] ? this.cleanup_time_ms : (java.lang.Long) defaultValue(fields()[3]);
        record.exit_code = fieldSetFlags()[4] ? this.exit_code : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ApplicationShutdown>
    WRITER$ = (org.apache.avro.io.DatumWriter<ApplicationShutdown>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ApplicationShutdown>
    READER$ = (org.apache.avro.io.DatumReader<ApplicationShutdown>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.shutdown_reason.ordinal());

    out.writeLong(this.uptime_seconds);

    if (this.final_memory_usage_mb == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.final_memory_usage_mb);
    }

    if (this.cleanup_time_ms == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.cleanup_time_ms);
    }

    out.writeInt(this.exit_code);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.shutdown_reason = com.tbw.security.securityevents.ShutdownReason.values()[in.readEnum()];

      this.uptime_seconds = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.final_memory_usage_mb = null;
      } else {
        this.final_memory_usage_mb = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.cleanup_time_ms = null;
      } else {
        this.cleanup_time_ms = in.readLong();
      }

      this.exit_code = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.shutdown_reason = com.tbw.security.securityevents.ShutdownReason.values()[in.readEnum()];
          break;

        case 1:
          this.uptime_seconds = in.readLong();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.final_memory_usage_mb = null;
          } else {
            this.final_memory_usage_mb = in.readLong();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.cleanup_time_ms = null;
          } else {
            this.cleanup_time_ms = in.readLong();
          }
          break;

        case 4:
          this.exit_code = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










