/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired when application starts up */
@org.apache.avro.specific.AvroGenerated
public class ApplicationStartup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5194121072665121278L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationStartup\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired when application starts up\",\"fields\":[{\"name\":\"startup_time_ms\",\"type\":\"long\",\"doc\":\"Time taken to start up in milliseconds\"},{\"name\":\"jvm_version\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"JVM version if applicable\",\"default\":null},{\"name\":\"memory_allocated_mb\",\"type\":[\"null\",\"long\"],\"doc\":\"Initial memory allocation in MB\",\"default\":null},{\"name\":\"configuration_profile\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Active configuration profile (e.g., 'prod', 'dev')\",\"default\":null},{\"name\":\"enabled_features\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"List of enabled feature flags or modules\",\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ApplicationStartup> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ApplicationStartup> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ApplicationStartup> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ApplicationStartup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ApplicationStartup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ApplicationStartup to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ApplicationStartup from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ApplicationStartup instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ApplicationStartup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Time taken to start up in milliseconds */
  private long startup_time_ms;
  /** JVM version if applicable */
  private java.lang.String jvm_version;
  /** Initial memory allocation in MB */
  private java.lang.Long memory_allocated_mb;
  /** Active configuration profile (e.g., 'prod', 'dev') */
  private java.lang.String configuration_profile;
  /** List of enabled feature flags or modules */
  private java.util.List<java.lang.String> enabled_features;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationStartup() {}

  /**
   * All-args constructor.
   * @param startup_time_ms Time taken to start up in milliseconds
   * @param jvm_version JVM version if applicable
   * @param memory_allocated_mb Initial memory allocation in MB
   * @param configuration_profile Active configuration profile (e.g., 'prod', 'dev')
   * @param enabled_features List of enabled feature flags or modules
   */
  public ApplicationStartup(java.lang.Long startup_time_ms, java.lang.String jvm_version, java.lang.Long memory_allocated_mb, java.lang.String configuration_profile, java.util.List<java.lang.String> enabled_features) {
    this.startup_time_ms = startup_time_ms;
    this.jvm_version = jvm_version;
    this.memory_allocated_mb = memory_allocated_mb;
    this.configuration_profile = configuration_profile;
    this.enabled_features = enabled_features;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return startup_time_ms;
    case 1: return jvm_version;
    case 2: return memory_allocated_mb;
    case 3: return configuration_profile;
    case 4: return enabled_features;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: startup_time_ms = (java.lang.Long)value$; break;
    case 1: jvm_version = value$ != null ? value$.toString() : null; break;
    case 2: memory_allocated_mb = (java.lang.Long)value$; break;
    case 3: configuration_profile = value$ != null ? value$.toString() : null; break;
    case 4: enabled_features = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'startup_time_ms' field.
   * @return Time taken to start up in milliseconds
   */
  public long getStartupTimeMs() {
    return startup_time_ms;
  }


  /**
   * Sets the value of the 'startup_time_ms' field.
   * Time taken to start up in milliseconds
   * @param value the value to set.
   */
  public void setStartupTimeMs(long value) {
    this.startup_time_ms = value;
  }

  /**
   * Gets the value of the 'jvm_version' field.
   * @return JVM version if applicable
   */
  public java.lang.String getJvmVersion() {
    return jvm_version;
  }


  /**
   * Sets the value of the 'jvm_version' field.
   * JVM version if applicable
   * @param value the value to set.
   */
  public void setJvmVersion(java.lang.String value) {
    this.jvm_version = value;
  }

  /**
   * Gets the value of the 'memory_allocated_mb' field.
   * @return Initial memory allocation in MB
   */
  public java.lang.Long getMemoryAllocatedMb() {
    return memory_allocated_mb;
  }


  /**
   * Sets the value of the 'memory_allocated_mb' field.
   * Initial memory allocation in MB
   * @param value the value to set.
   */
  public void setMemoryAllocatedMb(java.lang.Long value) {
    this.memory_allocated_mb = value;
  }

  /**
   * Gets the value of the 'configuration_profile' field.
   * @return Active configuration profile (e.g., 'prod', 'dev')
   */
  public java.lang.String getConfigurationProfile() {
    return configuration_profile;
  }


  /**
   * Sets the value of the 'configuration_profile' field.
   * Active configuration profile (e.g., 'prod', 'dev')
   * @param value the value to set.
   */
  public void setConfigurationProfile(java.lang.String value) {
    this.configuration_profile = value;
  }

  /**
   * Gets the value of the 'enabled_features' field.
   * @return List of enabled feature flags or modules
   */
  public java.util.List<java.lang.String> getEnabledFeatures() {
    return enabled_features;
  }


  /**
   * Sets the value of the 'enabled_features' field.
   * List of enabled feature flags or modules
   * @param value the value to set.
   */
  public void setEnabledFeatures(java.util.List<java.lang.String> value) {
    this.enabled_features = value;
  }

  /**
   * Creates a new ApplicationStartup RecordBuilder.
   * @return A new ApplicationStartup RecordBuilder
   */
  public static com.tbw.security.securityevents.ApplicationStartup.Builder newBuilder() {
    return new com.tbw.security.securityevents.ApplicationStartup.Builder();
  }

  /**
   * Creates a new ApplicationStartup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationStartup RecordBuilder
   */
  public static com.tbw.security.securityevents.ApplicationStartup.Builder newBuilder(com.tbw.security.securityevents.ApplicationStartup.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ApplicationStartup.Builder();
    } else {
      return new com.tbw.security.securityevents.ApplicationStartup.Builder(other);
    }
  }

  /**
   * Creates a new ApplicationStartup RecordBuilder by copying an existing ApplicationStartup instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationStartup RecordBuilder
   */
  public static com.tbw.security.securityevents.ApplicationStartup.Builder newBuilder(com.tbw.security.securityevents.ApplicationStartup other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ApplicationStartup.Builder();
    } else {
      return new com.tbw.security.securityevents.ApplicationStartup.Builder(other);
    }
  }

  /**
   * RecordBuilder for ApplicationStartup instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationStartup>
    implements org.apache.avro.data.RecordBuilder<ApplicationStartup> {

    /** Time taken to start up in milliseconds */
    private long startup_time_ms;
    /** JVM version if applicable */
    private java.lang.String jvm_version;
    /** Initial memory allocation in MB */
    private java.lang.Long memory_allocated_mb;
    /** Active configuration profile (e.g., 'prod', 'dev') */
    private java.lang.String configuration_profile;
    /** List of enabled feature flags or modules */
    private java.util.List<java.lang.String> enabled_features;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.ApplicationStartup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.startup_time_ms)) {
        this.startup_time_ms = data().deepCopy(fields()[0].schema(), other.startup_time_ms);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.jvm_version)) {
        this.jvm_version = data().deepCopy(fields()[1].schema(), other.jvm_version);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.memory_allocated_mb)) {
        this.memory_allocated_mb = data().deepCopy(fields()[2].schema(), other.memory_allocated_mb);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.configuration_profile)) {
        this.configuration_profile = data().deepCopy(fields()[3].schema(), other.configuration_profile);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.enabled_features)) {
        this.enabled_features = data().deepCopy(fields()[4].schema(), other.enabled_features);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationStartup instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.ApplicationStartup other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.startup_time_ms)) {
        this.startup_time_ms = data().deepCopy(fields()[0].schema(), other.startup_time_ms);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jvm_version)) {
        this.jvm_version = data().deepCopy(fields()[1].schema(), other.jvm_version);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.memory_allocated_mb)) {
        this.memory_allocated_mb = data().deepCopy(fields()[2].schema(), other.memory_allocated_mb);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.configuration_profile)) {
        this.configuration_profile = data().deepCopy(fields()[3].schema(), other.configuration_profile);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.enabled_features)) {
        this.enabled_features = data().deepCopy(fields()[4].schema(), other.enabled_features);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'startup_time_ms' field.
      * Time taken to start up in milliseconds
      * @return The value.
      */
    public long getStartupTimeMs() {
      return startup_time_ms;
    }


    /**
      * Sets the value of the 'startup_time_ms' field.
      * Time taken to start up in milliseconds
      * @param value The value of 'startup_time_ms'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder setStartupTimeMs(long value) {
      validate(fields()[0], value);
      this.startup_time_ms = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'startup_time_ms' field has been set.
      * Time taken to start up in milliseconds
      * @return True if the 'startup_time_ms' field has been set, false otherwise.
      */
    public boolean hasStartupTimeMs() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'startup_time_ms' field.
      * Time taken to start up in milliseconds
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder clearStartupTimeMs() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'jvm_version' field.
      * JVM version if applicable
      * @return The value.
      */
    public java.lang.String getJvmVersion() {
      return jvm_version;
    }


    /**
      * Sets the value of the 'jvm_version' field.
      * JVM version if applicable
      * @param value The value of 'jvm_version'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder setJvmVersion(java.lang.String value) {
      validate(fields()[1], value);
      this.jvm_version = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'jvm_version' field has been set.
      * JVM version if applicable
      * @return True if the 'jvm_version' field has been set, false otherwise.
      */
    public boolean hasJvmVersion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'jvm_version' field.
      * JVM version if applicable
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder clearJvmVersion() {
      jvm_version = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'memory_allocated_mb' field.
      * Initial memory allocation in MB
      * @return The value.
      */
    public java.lang.Long getMemoryAllocatedMb() {
      return memory_allocated_mb;
    }


    /**
      * Sets the value of the 'memory_allocated_mb' field.
      * Initial memory allocation in MB
      * @param value The value of 'memory_allocated_mb'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder setMemoryAllocatedMb(java.lang.Long value) {
      validate(fields()[2], value);
      this.memory_allocated_mb = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'memory_allocated_mb' field has been set.
      * Initial memory allocation in MB
      * @return True if the 'memory_allocated_mb' field has been set, false otherwise.
      */
    public boolean hasMemoryAllocatedMb() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'memory_allocated_mb' field.
      * Initial memory allocation in MB
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder clearMemoryAllocatedMb() {
      memory_allocated_mb = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'configuration_profile' field.
      * Active configuration profile (e.g., 'prod', 'dev')
      * @return The value.
      */
    public java.lang.String getConfigurationProfile() {
      return configuration_profile;
    }


    /**
      * Sets the value of the 'configuration_profile' field.
      * Active configuration profile (e.g., 'prod', 'dev')
      * @param value The value of 'configuration_profile'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder setConfigurationProfile(java.lang.String value) {
      validate(fields()[3], value);
      this.configuration_profile = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'configuration_profile' field has been set.
      * Active configuration profile (e.g., 'prod', 'dev')
      * @return True if the 'configuration_profile' field has been set, false otherwise.
      */
    public boolean hasConfigurationProfile() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'configuration_profile' field.
      * Active configuration profile (e.g., 'prod', 'dev')
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder clearConfigurationProfile() {
      configuration_profile = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'enabled_features' field.
      * List of enabled feature flags or modules
      * @return The value.
      */
    public java.util.List<java.lang.String> getEnabledFeatures() {
      return enabled_features;
    }


    /**
      * Sets the value of the 'enabled_features' field.
      * List of enabled feature flags or modules
      * @param value The value of 'enabled_features'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder setEnabledFeatures(java.util.List<java.lang.String> value) {
      validate(fields()[4], value);
      this.enabled_features = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'enabled_features' field has been set.
      * List of enabled feature flags or modules
      * @return True if the 'enabled_features' field has been set, false otherwise.
      */
    public boolean hasEnabledFeatures() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'enabled_features' field.
      * List of enabled feature flags or modules
      * @return This builder.
      */
    public com.tbw.security.securityevents.ApplicationStartup.Builder clearEnabledFeatures() {
      enabled_features = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ApplicationStartup build() {
      try {
        ApplicationStartup record = new ApplicationStartup();
        record.startup_time_ms = fieldSetFlags()[0] ? this.startup_time_ms : (java.lang.Long) defaultValue(fields()[0]);
        record.jvm_version = fieldSetFlags()[1] ? this.jvm_version : (java.lang.String) defaultValue(fields()[1]);
        record.memory_allocated_mb = fieldSetFlags()[2] ? this.memory_allocated_mb : (java.lang.Long) defaultValue(fields()[2]);
        record.configuration_profile = fieldSetFlags()[3] ? this.configuration_profile : (java.lang.String) defaultValue(fields()[3]);
        record.enabled_features = fieldSetFlags()[4] ? this.enabled_features : (java.util.List<java.lang.String>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ApplicationStartup>
    WRITER$ = (org.apache.avro.io.DatumWriter<ApplicationStartup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ApplicationStartup>
    READER$ = (org.apache.avro.io.DatumReader<ApplicationStartup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.startup_time_ms);

    if (this.jvm_version == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.jvm_version);
    }

    if (this.memory_allocated_mb == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.memory_allocated_mb);
    }

    if (this.configuration_profile == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.configuration_profile);
    }

    long size0 = this.enabled_features.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.enabled_features) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.startup_time_ms = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.jvm_version = null;
      } else {
        this.jvm_version = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.memory_allocated_mb = null;
      } else {
        this.memory_allocated_mb = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.configuration_profile = null;
      } else {
        this.configuration_profile = in.readString();
      }

      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.enabled_features;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("enabled_features").schema());
        this.enabled_features = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.startup_time_ms = in.readLong();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.jvm_version = null;
          } else {
            this.jvm_version = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.memory_allocated_mb = null;
          } else {
            this.memory_allocated_mb = in.readLong();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.configuration_profile = null;
          } else {
            this.configuration_profile = in.readString();
          }
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.enabled_features;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("enabled_features").schema());
            this.enabled_features = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










