/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired when configuration changes */
@org.apache.avro.specific.AvroGenerated
public class ConfigurationChange extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2004099644285197193L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ConfigurationChange\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired when configuration changes\",\"fields\":[{\"name\":\"config_key\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Configuration key that changed\"},{\"name\":\"old_value\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Previous configuration value (null if newly added)\",\"default\":null},{\"name\":\"new_value\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"New configuration value (null if deleted)\",\"default\":null},{\"name\":\"change_source\",\"type\":{\"type\":\"enum\",\"name\":\"ConfigSource\",\"symbols\":[\"FILE\",\"ENVIRONMENT\",\"DATABASE\",\"REMOTE_CONFIG\",\"ADMIN_INTERFACE\",\"API\"],\"default\":\"FILE\"},\"doc\":\"Source of the configuration change\"},{\"name\":\"requires_restart\",\"type\":\"boolean\",\"doc\":\"Whether this change requires application restart\",\"default\":false}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ConfigurationChange> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ConfigurationChange> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ConfigurationChange> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ConfigurationChange> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ConfigurationChange> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ConfigurationChange to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ConfigurationChange from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ConfigurationChange instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ConfigurationChange fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Configuration key that changed */
  private java.lang.String config_key;
  /** Previous configuration value (null if newly added) */
  private java.lang.String old_value;
  /** New configuration value (null if deleted) */
  private java.lang.String new_value;
  /** Source of the configuration change */
  private com.tbw.security.securityevents.ConfigSource change_source;
  /** Whether this change requires application restart */
  private boolean requires_restart;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ConfigurationChange() {}

  /**
   * All-args constructor.
   * @param config_key Configuration key that changed
   * @param old_value Previous configuration value (null if newly added)
   * @param new_value New configuration value (null if deleted)
   * @param change_source Source of the configuration change
   * @param requires_restart Whether this change requires application restart
   */
  public ConfigurationChange(java.lang.String config_key, java.lang.String old_value, java.lang.String new_value, com.tbw.security.securityevents.ConfigSource change_source, java.lang.Boolean requires_restart) {
    this.config_key = config_key;
    this.old_value = old_value;
    this.new_value = new_value;
    this.change_source = change_source;
    this.requires_restart = requires_restart;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return config_key;
    case 1: return old_value;
    case 2: return new_value;
    case 3: return change_source;
    case 4: return requires_restart;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: config_key = value$ != null ? value$.toString() : null; break;
    case 1: old_value = value$ != null ? value$.toString() : null; break;
    case 2: new_value = value$ != null ? value$.toString() : null; break;
    case 3: change_source = (com.tbw.security.securityevents.ConfigSource)value$; break;
    case 4: requires_restart = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'config_key' field.
   * @return Configuration key that changed
   */
  public java.lang.String getConfigKey() {
    return config_key;
  }


  /**
   * Sets the value of the 'config_key' field.
   * Configuration key that changed
   * @param value the value to set.
   */
  public void setConfigKey(java.lang.String value) {
    this.config_key = value;
  }

  /**
   * Gets the value of the 'old_value' field.
   * @return Previous configuration value (null if newly added)
   */
  public java.lang.String getOldValue() {
    return old_value;
  }


  /**
   * Sets the value of the 'old_value' field.
   * Previous configuration value (null if newly added)
   * @param value the value to set.
   */
  public void setOldValue(java.lang.String value) {
    this.old_value = value;
  }

  /**
   * Gets the value of the 'new_value' field.
   * @return New configuration value (null if deleted)
   */
  public java.lang.String getNewValue() {
    return new_value;
  }


  /**
   * Sets the value of the 'new_value' field.
   * New configuration value (null if deleted)
   * @param value the value to set.
   */
  public void setNewValue(java.lang.String value) {
    this.new_value = value;
  }

  /**
   * Gets the value of the 'change_source' field.
   * @return Source of the configuration change
   */
  public com.tbw.security.securityevents.ConfigSource getChangeSource() {
    return change_source;
  }


  /**
   * Sets the value of the 'change_source' field.
   * Source of the configuration change
   * @param value the value to set.
   */
  public void setChangeSource(com.tbw.security.securityevents.ConfigSource value) {
    this.change_source = value;
  }

  /**
   * Gets the value of the 'requires_restart' field.
   * @return Whether this change requires application restart
   */
  public boolean getRequiresRestart() {
    return requires_restart;
  }


  /**
   * Sets the value of the 'requires_restart' field.
   * Whether this change requires application restart
   * @param value the value to set.
   */
  public void setRequiresRestart(boolean value) {
    this.requires_restart = value;
  }

  /**
   * Creates a new ConfigurationChange RecordBuilder.
   * @return A new ConfigurationChange RecordBuilder
   */
  public static com.tbw.security.securityevents.ConfigurationChange.Builder newBuilder() {
    return new com.tbw.security.securityevents.ConfigurationChange.Builder();
  }

  /**
   * Creates a new ConfigurationChange RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ConfigurationChange RecordBuilder
   */
  public static com.tbw.security.securityevents.ConfigurationChange.Builder newBuilder(com.tbw.security.securityevents.ConfigurationChange.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ConfigurationChange.Builder();
    } else {
      return new com.tbw.security.securityevents.ConfigurationChange.Builder(other);
    }
  }

  /**
   * Creates a new ConfigurationChange RecordBuilder by copying an existing ConfigurationChange instance.
   * @param other The existing instance to copy.
   * @return A new ConfigurationChange RecordBuilder
   */
  public static com.tbw.security.securityevents.ConfigurationChange.Builder newBuilder(com.tbw.security.securityevents.ConfigurationChange other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ConfigurationChange.Builder();
    } else {
      return new com.tbw.security.securityevents.ConfigurationChange.Builder(other);
    }
  }

  /**
   * RecordBuilder for ConfigurationChange instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConfigurationChange>
    implements org.apache.avro.data.RecordBuilder<ConfigurationChange> {

    /** Configuration key that changed */
    private java.lang.String config_key;
    /** Previous configuration value (null if newly added) */
    private java.lang.String old_value;
    /** New configuration value (null if deleted) */
    private java.lang.String new_value;
    /** Source of the configuration change */
    private com.tbw.security.securityevents.ConfigSource change_source;
    /** Whether this change requires application restart */
    private boolean requires_restart;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.ConfigurationChange.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.config_key)) {
        this.config_key = data().deepCopy(fields()[0].schema(), other.config_key);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.old_value)) {
        this.old_value = data().deepCopy(fields()[1].schema(), other.old_value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.new_value)) {
        this.new_value = data().deepCopy(fields()[2].schema(), other.new_value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.change_source)) {
        this.change_source = data().deepCopy(fields()[3].schema(), other.change_source);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.requires_restart)) {
        this.requires_restart = data().deepCopy(fields()[4].schema(), other.requires_restart);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ConfigurationChange instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.ConfigurationChange other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.config_key)) {
        this.config_key = data().deepCopy(fields()[0].schema(), other.config_key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.old_value)) {
        this.old_value = data().deepCopy(fields()[1].schema(), other.old_value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.new_value)) {
        this.new_value = data().deepCopy(fields()[2].schema(), other.new_value);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.change_source)) {
        this.change_source = data().deepCopy(fields()[3].schema(), other.change_source);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.requires_restart)) {
        this.requires_restart = data().deepCopy(fields()[4].schema(), other.requires_restart);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'config_key' field.
      * Configuration key that changed
      * @return The value.
      */
    public java.lang.String getConfigKey() {
      return config_key;
    }


    /**
      * Sets the value of the 'config_key' field.
      * Configuration key that changed
      * @param value The value of 'config_key'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder setConfigKey(java.lang.String value) {
      validate(fields()[0], value);
      this.config_key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'config_key' field has been set.
      * Configuration key that changed
      * @return True if the 'config_key' field has been set, false otherwise.
      */
    public boolean hasConfigKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'config_key' field.
      * Configuration key that changed
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder clearConfigKey() {
      config_key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_value' field.
      * Previous configuration value (null if newly added)
      * @return The value.
      */
    public java.lang.String getOldValue() {
      return old_value;
    }


    /**
      * Sets the value of the 'old_value' field.
      * Previous configuration value (null if newly added)
      * @param value The value of 'old_value'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder setOldValue(java.lang.String value) {
      validate(fields()[1], value);
      this.old_value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'old_value' field has been set.
      * Previous configuration value (null if newly added)
      * @return True if the 'old_value' field has been set, false otherwise.
      */
    public boolean hasOldValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'old_value' field.
      * Previous configuration value (null if newly added)
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder clearOldValue() {
      old_value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_value' field.
      * New configuration value (null if deleted)
      * @return The value.
      */
    public java.lang.String getNewValue() {
      return new_value;
    }


    /**
      * Sets the value of the 'new_value' field.
      * New configuration value (null if deleted)
      * @param value The value of 'new_value'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder setNewValue(java.lang.String value) {
      validate(fields()[2], value);
      this.new_value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'new_value' field has been set.
      * New configuration value (null if deleted)
      * @return True if the 'new_value' field has been set, false otherwise.
      */
    public boolean hasNewValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'new_value' field.
      * New configuration value (null if deleted)
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder clearNewValue() {
      new_value = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'change_source' field.
      * Source of the configuration change
      * @return The value.
      */
    public com.tbw.security.securityevents.ConfigSource getChangeSource() {
      return change_source;
    }


    /**
      * Sets the value of the 'change_source' field.
      * Source of the configuration change
      * @param value The value of 'change_source'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder setChangeSource(com.tbw.security.securityevents.ConfigSource value) {
      validate(fields()[3], value);
      this.change_source = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'change_source' field has been set.
      * Source of the configuration change
      * @return True if the 'change_source' field has been set, false otherwise.
      */
    public boolean hasChangeSource() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'change_source' field.
      * Source of the configuration change
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder clearChangeSource() {
      change_source = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'requires_restart' field.
      * Whether this change requires application restart
      * @return The value.
      */
    public boolean getRequiresRestart() {
      return requires_restart;
    }


    /**
      * Sets the value of the 'requires_restart' field.
      * Whether this change requires application restart
      * @param value The value of 'requires_restart'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder setRequiresRestart(boolean value) {
      validate(fields()[4], value);
      this.requires_restart = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'requires_restart' field has been set.
      * Whether this change requires application restart
      * @return True if the 'requires_restart' field has been set, false otherwise.
      */
    public boolean hasRequiresRestart() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'requires_restart' field.
      * Whether this change requires application restart
      * @return This builder.
      */
    public com.tbw.security.securityevents.ConfigurationChange.Builder clearRequiresRestart() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ConfigurationChange build() {
      try {
        ConfigurationChange record = new ConfigurationChange();
        record.config_key = fieldSetFlags()[0] ? this.config_key : (java.lang.String) defaultValue(fields()[0]);
        record.old_value = fieldSetFlags()[1] ? this.old_value : (java.lang.String) defaultValue(fields()[1]);
        record.new_value = fieldSetFlags()[2] ? this.new_value : (java.lang.String) defaultValue(fields()[2]);
        record.change_source = fieldSetFlags()[3] ? this.change_source : (com.tbw.security.securityevents.ConfigSource) defaultValue(fields()[3]);
        record.requires_restart = fieldSetFlags()[4] ? this.requires_restart : (java.lang.Boolean) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ConfigurationChange>
    WRITER$ = (org.apache.avro.io.DatumWriter<ConfigurationChange>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ConfigurationChange>
    READER$ = (org.apache.avro.io.DatumReader<ConfigurationChange>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.config_key);

    if (this.old_value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.old_value);
    }

    if (this.new_value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.new_value);
    }

    out.writeEnum(this.change_source.ordinal());

    out.writeBoolean(this.requires_restart);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.config_key = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.old_value = null;
      } else {
        this.old_value = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.new_value = null;
      } else {
        this.new_value = in.readString();
      }

      this.change_source = com.tbw.security.securityevents.ConfigSource.values()[in.readEnum()];

      this.requires_restart = in.readBoolean();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.config_key = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.old_value = null;
          } else {
            this.old_value = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.new_value = null;
          } else {
            this.new_value = in.readString();
          }
          break;

        case 3:
          this.change_source = com.tbw.security.securityevents.ConfigSource.values()[in.readEnum()];
          break;

        case 4:
          this.requires_restart = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










