/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum ConfigSource implements org.apache.avro.generic.GenericEnumSymbol<ConfigSource> {
  FILE, ENVIRONMENT, DATABASE, REMOTE_CONFIG, ADMIN_INTERFACE, API  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConfigSource\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"FILE\",\"ENVIRONMENT\",\"DATABASE\",\"REMOTE_CONFIG\",\"ADMIN_INTERFACE\",\"API\"],\"default\":\"FILE\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
