/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum DatabaseOperationType implements org.apache.avro.generic.GenericEnumSymbol<DatabaseOperationType> {
  MIGRATION, BACKUP, RESTORE, INDEX_REBUILD, MAINTENANCE, CONNECTION_POOL_EVENT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DatabaseOperationType\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"MIGRATION\",\"BACKUP\",\"RESTORE\",\"INDEX_REBUILD\",\"MAINTENANCE\",\"CONNECTION_POOL_EVENT\"],\"default\":\"MIGRATION\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
