/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired for significant database operations */
@org.apache.avro.specific.AvroGenerated
public class DatabaseOperation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6616514660961156488L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DatabaseOperation\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired for significant database operations\",\"fields\":[{\"name\":\"operation_type\",\"type\":{\"type\":\"enum\",\"name\":\"DatabaseOperationType\",\"symbols\":[\"MIGRATION\",\"BACKUP\",\"RESTORE\",\"INDEX_REBUILD\",\"MAINTENANCE\",\"CONNECTION_POOL_EVENT\"],\"default\":\"MIGRATION\"},\"doc\":\"Type of database operation\"},{\"name\":\"database_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the database\"},{\"name\":\"operation_status\",\"type\":{\"type\":\"enum\",\"name\":\"OperationStatus\",\"symbols\":[\"STARTED\",\"IN_PROGRESS\",\"COMPLETED\",\"FAILED\",\"CANCELLED\"],\"default\":\"STARTED\"},\"doc\":\"Status of the operation\"},{\"name\":\"duration_ms\",\"type\":[\"null\",\"long\"],\"doc\":\"Operation duration in milliseconds (null if still running)\",\"default\":null},{\"name\":\"affected_tables\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"List of tables affected by the operation\",\"default\":[]},{\"name\":\"error_message\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Error message if operation failed\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DatabaseOperation> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DatabaseOperation> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DatabaseOperation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DatabaseOperation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DatabaseOperation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DatabaseOperation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DatabaseOperation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DatabaseOperation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DatabaseOperation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Type of database operation */
  private com.tbw.security.securityevents.DatabaseOperationType operation_type;
  /** Name of the database */
  private java.lang.String database_name;
  /** Status of the operation */
  private com.tbw.security.securityevents.OperationStatus operation_status;
  /** Operation duration in milliseconds (null if still running) */
  private java.lang.Long duration_ms;
  /** List of tables affected by the operation */
  private java.util.List<java.lang.String> affected_tables;
  /** Error message if operation failed */
  private java.lang.String error_message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DatabaseOperation() {}

  /**
   * All-args constructor.
   * @param operation_type Type of database operation
   * @param database_name Name of the database
   * @param operation_status Status of the operation
   * @param duration_ms Operation duration in milliseconds (null if still running)
   * @param affected_tables List of tables affected by the operation
   * @param error_message Error message if operation failed
   */
  public DatabaseOperation(com.tbw.security.securityevents.DatabaseOperationType operation_type, java.lang.String database_name, com.tbw.security.securityevents.OperationStatus operation_status, java.lang.Long duration_ms, java.util.List<java.lang.String> affected_tables, java.lang.String error_message) {
    this.operation_type = operation_type;
    this.database_name = database_name;
    this.operation_status = operation_status;
    this.duration_ms = duration_ms;
    this.affected_tables = affected_tables;
    this.error_message = error_message;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return operation_type;
    case 1: return database_name;
    case 2: return operation_status;
    case 3: return duration_ms;
    case 4: return affected_tables;
    case 5: return error_message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: operation_type = (com.tbw.security.securityevents.DatabaseOperationType)value$; break;
    case 1: database_name = value$ != null ? value$.toString() : null; break;
    case 2: operation_status = (com.tbw.security.securityevents.OperationStatus)value$; break;
    case 3: duration_ms = (java.lang.Long)value$; break;
    case 4: affected_tables = (java.util.List<java.lang.String>)value$; break;
    case 5: error_message = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'operation_type' field.
   * @return Type of database operation
   */
  public com.tbw.security.securityevents.DatabaseOperationType getOperationType() {
    return operation_type;
  }


  /**
   * Sets the value of the 'operation_type' field.
   * Type of database operation
   * @param value the value to set.
   */
  public void setOperationType(com.tbw.security.securityevents.DatabaseOperationType value) {
    this.operation_type = value;
  }

  /**
   * Gets the value of the 'database_name' field.
   * @return Name of the database
   */
  public java.lang.String getDatabaseName() {
    return database_name;
  }


  /**
   * Sets the value of the 'database_name' field.
   * Name of the database
   * @param value the value to set.
   */
  public void setDatabaseName(java.lang.String value) {
    this.database_name = value;
  }

  /**
   * Gets the value of the 'operation_status' field.
   * @return Status of the operation
   */
  public com.tbw.security.securityevents.OperationStatus getOperationStatus() {
    return operation_status;
  }


  /**
   * Sets the value of the 'operation_status' field.
   * Status of the operation
   * @param value the value to set.
   */
  public void setOperationStatus(com.tbw.security.securityevents.OperationStatus value) {
    this.operation_status = value;
  }

  /**
   * Gets the value of the 'duration_ms' field.
   * @return Operation duration in milliseconds (null if still running)
   */
  public java.lang.Long getDurationMs() {
    return duration_ms;
  }


  /**
   * Sets the value of the 'duration_ms' field.
   * Operation duration in milliseconds (null if still running)
   * @param value the value to set.
   */
  public void setDurationMs(java.lang.Long value) {
    this.duration_ms = value;
  }

  /**
   * Gets the value of the 'affected_tables' field.
   * @return List of tables affected by the operation
   */
  public java.util.List<java.lang.String> getAffectedTables() {
    return affected_tables;
  }


  /**
   * Sets the value of the 'affected_tables' field.
   * List of tables affected by the operation
   * @param value the value to set.
   */
  public void setAffectedTables(java.util.List<java.lang.String> value) {
    this.affected_tables = value;
  }

  /**
   * Gets the value of the 'error_message' field.
   * @return Error message if operation failed
   */
  public java.lang.String getErrorMessage() {
    return error_message;
  }


  /**
   * Sets the value of the 'error_message' field.
   * Error message if operation failed
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.error_message = value;
  }

  /**
   * Creates a new DatabaseOperation RecordBuilder.
   * @return A new DatabaseOperation RecordBuilder
   */
  public static com.tbw.security.securityevents.DatabaseOperation.Builder newBuilder() {
    return new com.tbw.security.securityevents.DatabaseOperation.Builder();
  }

  /**
   * Creates a new DatabaseOperation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DatabaseOperation RecordBuilder
   */
  public static com.tbw.security.securityevents.DatabaseOperation.Builder newBuilder(com.tbw.security.securityevents.DatabaseOperation.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.DatabaseOperation.Builder();
    } else {
      return new com.tbw.security.securityevents.DatabaseOperation.Builder(other);
    }
  }

  /**
   * Creates a new DatabaseOperation RecordBuilder by copying an existing DatabaseOperation instance.
   * @param other The existing instance to copy.
   * @return A new DatabaseOperation RecordBuilder
   */
  public static com.tbw.security.securityevents.DatabaseOperation.Builder newBuilder(com.tbw.security.securityevents.DatabaseOperation other) {
    if (other == null) {
      return new com.tbw.security.securityevents.DatabaseOperation.Builder();
    } else {
      return new com.tbw.security.securityevents.DatabaseOperation.Builder(other);
    }
  }

  /**
   * RecordBuilder for DatabaseOperation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DatabaseOperation>
    implements org.apache.avro.data.RecordBuilder<DatabaseOperation> {

    /** Type of database operation */
    private com.tbw.security.securityevents.DatabaseOperationType operation_type;
    /** Name of the database */
    private java.lang.String database_name;
    /** Status of the operation */
    private com.tbw.security.securityevents.OperationStatus operation_status;
    /** Operation duration in milliseconds (null if still running) */
    private java.lang.Long duration_ms;
    /** List of tables affected by the operation */
    private java.util.List<java.lang.String> affected_tables;
    /** Error message if operation failed */
    private java.lang.String error_message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.DatabaseOperation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.operation_type)) {
        this.operation_type = data().deepCopy(fields()[0].schema(), other.operation_type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.database_name)) {
        this.database_name = data().deepCopy(fields()[1].schema(), other.database_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.operation_status)) {
        this.operation_status = data().deepCopy(fields()[2].schema(), other.operation_status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.duration_ms)) {
        this.duration_ms = data().deepCopy(fields()[3].schema(), other.duration_ms);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.affected_tables)) {
        this.affected_tables = data().deepCopy(fields()[4].schema(), other.affected_tables);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.error_message)) {
        this.error_message = data().deepCopy(fields()[5].schema(), other.error_message);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing DatabaseOperation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.DatabaseOperation other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.operation_type)) {
        this.operation_type = data().deepCopy(fields()[0].schema(), other.operation_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.database_name)) {
        this.database_name = data().deepCopy(fields()[1].schema(), other.database_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.operation_status)) {
        this.operation_status = data().deepCopy(fields()[2].schema(), other.operation_status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.duration_ms)) {
        this.duration_ms = data().deepCopy(fields()[3].schema(), other.duration_ms);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.affected_tables)) {
        this.affected_tables = data().deepCopy(fields()[4].schema(), other.affected_tables);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.error_message)) {
        this.error_message = data().deepCopy(fields()[5].schema(), other.error_message);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'operation_type' field.
      * Type of database operation
      * @return The value.
      */
    public com.tbw.security.securityevents.DatabaseOperationType getOperationType() {
      return operation_type;
    }


    /**
      * Sets the value of the 'operation_type' field.
      * Type of database operation
      * @param value The value of 'operation_type'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder setOperationType(com.tbw.security.securityevents.DatabaseOperationType value) {
      validate(fields()[0], value);
      this.operation_type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'operation_type' field has been set.
      * Type of database operation
      * @return True if the 'operation_type' field has been set, false otherwise.
      */
    public boolean hasOperationType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'operation_type' field.
      * Type of database operation
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder clearOperationType() {
      operation_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'database_name' field.
      * Name of the database
      * @return The value.
      */
    public java.lang.String getDatabaseName() {
      return database_name;
    }


    /**
      * Sets the value of the 'database_name' field.
      * Name of the database
      * @param value The value of 'database_name'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder setDatabaseName(java.lang.String value) {
      validate(fields()[1], value);
      this.database_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'database_name' field has been set.
      * Name of the database
      * @return True if the 'database_name' field has been set, false otherwise.
      */
    public boolean hasDatabaseName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'database_name' field.
      * Name of the database
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder clearDatabaseName() {
      database_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'operation_status' field.
      * Status of the operation
      * @return The value.
      */
    public com.tbw.security.securityevents.OperationStatus getOperationStatus() {
      return operation_status;
    }


    /**
      * Sets the value of the 'operation_status' field.
      * Status of the operation
      * @param value The value of 'operation_status'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder setOperationStatus(com.tbw.security.securityevents.OperationStatus value) {
      validate(fields()[2], value);
      this.operation_status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'operation_status' field has been set.
      * Status of the operation
      * @return True if the 'operation_status' field has been set, false otherwise.
      */
    public boolean hasOperationStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'operation_status' field.
      * Status of the operation
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder clearOperationStatus() {
      operation_status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration_ms' field.
      * Operation duration in milliseconds (null if still running)
      * @return The value.
      */
    public java.lang.Long getDurationMs() {
      return duration_ms;
    }


    /**
      * Sets the value of the 'duration_ms' field.
      * Operation duration in milliseconds (null if still running)
      * @param value The value of 'duration_ms'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder setDurationMs(java.lang.Long value) {
      validate(fields()[3], value);
      this.duration_ms = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'duration_ms' field has been set.
      * Operation duration in milliseconds (null if still running)
      * @return True if the 'duration_ms' field has been set, false otherwise.
      */
    public boolean hasDurationMs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'duration_ms' field.
      * Operation duration in milliseconds (null if still running)
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder clearDurationMs() {
      duration_ms = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'affected_tables' field.
      * List of tables affected by the operation
      * @return The value.
      */
    public java.util.List<java.lang.String> getAffectedTables() {
      return affected_tables;
    }


    /**
      * Sets the value of the 'affected_tables' field.
      * List of tables affected by the operation
      * @param value The value of 'affected_tables'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder setAffectedTables(java.util.List<java.lang.String> value) {
      validate(fields()[4], value);
      this.affected_tables = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'affected_tables' field has been set.
      * List of tables affected by the operation
      * @return True if the 'affected_tables' field has been set, false otherwise.
      */
    public boolean hasAffectedTables() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'affected_tables' field.
      * List of tables affected by the operation
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder clearAffectedTables() {
      affected_tables = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'error_message' field.
      * Error message if operation failed
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return error_message;
    }


    /**
      * Sets the value of the 'error_message' field.
      * Error message if operation failed
      * @param value The value of 'error_message'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[5], value);
      this.error_message = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'error_message' field has been set.
      * Error message if operation failed
      * @return True if the 'error_message' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'error_message' field.
      * Error message if operation failed
      * @return This builder.
      */
    public com.tbw.security.securityevents.DatabaseOperation.Builder clearErrorMessage() {
      error_message = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DatabaseOperation build() {
      try {
        DatabaseOperation record = new DatabaseOperation();
        record.operation_type = fieldSetFlags()[0] ? this.operation_type : (com.tbw.security.securityevents.DatabaseOperationType) defaultValue(fields()[0]);
        record.database_name = fieldSetFlags()[1] ? this.database_name : (java.lang.String) defaultValue(fields()[1]);
        record.operation_status = fieldSetFlags()[2] ? this.operation_status : (com.tbw.security.securityevents.OperationStatus) defaultValue(fields()[2]);
        record.duration_ms = fieldSetFlags()[3] ? this.duration_ms : (java.lang.Long) defaultValue(fields()[3]);
        record.affected_tables = fieldSetFlags()[4] ? this.affected_tables : (java.util.List<java.lang.String>) defaultValue(fields()[4]);
        record.error_message = fieldSetFlags()[5] ? this.error_message : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DatabaseOperation>
    WRITER$ = (org.apache.avro.io.DatumWriter<DatabaseOperation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DatabaseOperation>
    READER$ = (org.apache.avro.io.DatumReader<DatabaseOperation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.operation_type.ordinal());

    out.writeString(this.database_name);

    out.writeEnum(this.operation_status.ordinal());

    if (this.duration_ms == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.duration_ms);
    }

    long size0 = this.affected_tables.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.affected_tables) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    if (this.error_message == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.error_message);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.operation_type = com.tbw.security.securityevents.DatabaseOperationType.values()[in.readEnum()];

      this.database_name = in.readString();

      this.operation_status = com.tbw.security.securityevents.OperationStatus.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.duration_ms = null;
      } else {
        this.duration_ms = in.readLong();
      }

      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.affected_tables;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("affected_tables").schema());
        this.affected_tables = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.error_message = null;
      } else {
        this.error_message = in.readString();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.operation_type = com.tbw.security.securityevents.DatabaseOperationType.values()[in.readEnum()];
          break;

        case 1:
          this.database_name = in.readString();
          break;

        case 2:
          this.operation_status = com.tbw.security.securityevents.OperationStatus.values()[in.readEnum()];
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.duration_ms = null;
          } else {
            this.duration_ms = in.readLong();
          }
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.affected_tables;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("affected_tables").schema());
            this.affected_tables = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.error_message = null;
          } else {
            this.error_message = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










