/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum DeploymentStage implements org.apache.avro.generic.GenericEnumSymbol<DeploymentStage> {
  STARTED, VALIDATING, DEPLOYING, HEALTH_CHECKING, COMPLETED, ROLLED_BACK, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DeploymentStage\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"STARTED\",\"VALIDATING\",\"DEPLOYING\",\"HEALTH_CHECKING\",\"COMPLETED\",\"ROLLED_BACK\",\"FAILED\"],\"default\":\"STARTED\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
