/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired during deployment lifecycle */
@org.apache.avro.specific.AvroGenerated
public class DeploymentEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7560243314082963589L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeploymentEvent\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired during deployment lifecycle\",\"fields\":[{\"name\":\"deployment_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier for this deployment\"},{\"name\":\"deployment_stage\",\"type\":{\"type\":\"enum\",\"name\":\"DeploymentStage\",\"symbols\":[\"STARTED\",\"VALIDATING\",\"DEPLOYING\",\"HEALTH_CHECKING\",\"COMPLETED\",\"ROLLED_BACK\",\"FAILED\"],\"default\":\"STARTED\"},\"doc\":\"Current stage of deployment\"},{\"name\":\"from_version\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Version being replaced (null for initial deployment)\",\"default\":null},{\"name\":\"to_version\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Version being deployed\"},{\"name\":\"deployment_strategy\",\"type\":{\"type\":\"enum\",\"name\":\"DeploymentStrategy\",\"symbols\":[\"BLUE_GREEN\",\"ROLLING\",\"CANARY\",\"RECREATE\"],\"default\":\"ROLLING\"},\"doc\":\"Deployment strategy used\"},{\"name\":\"rollback_reason\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Reason for rollback if applicable\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeploymentEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeploymentEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeploymentEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeploymentEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeploymentEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeploymentEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeploymentEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeploymentEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeploymentEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for this deployment */
  private java.lang.String deployment_id;
  /** Current stage of deployment */
  private com.tbw.security.securityevents.DeploymentStage deployment_stage;
  /** Version being replaced (null for initial deployment) */
  private java.lang.String from_version;
  /** Version being deployed */
  private java.lang.String to_version;
  /** Deployment strategy used */
  private com.tbw.security.securityevents.DeploymentStrategy deployment_strategy;
  /** Reason for rollback if applicable */
  private java.lang.String rollback_reason;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeploymentEvent() {}

  /**
   * All-args constructor.
   * @param deployment_id Unique identifier for this deployment
   * @param deployment_stage Current stage of deployment
   * @param from_version Version being replaced (null for initial deployment)
   * @param to_version Version being deployed
   * @param deployment_strategy Deployment strategy used
   * @param rollback_reason Reason for rollback if applicable
   */
  public DeploymentEvent(java.lang.String deployment_id, com.tbw.security.securityevents.DeploymentStage deployment_stage, java.lang.String from_version, java.lang.String to_version, com.tbw.security.securityevents.DeploymentStrategy deployment_strategy, java.lang.String rollback_reason) {
    this.deployment_id = deployment_id;
    this.deployment_stage = deployment_stage;
    this.from_version = from_version;
    this.to_version = to_version;
    this.deployment_strategy = deployment_strategy;
    this.rollback_reason = rollback_reason;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deployment_id;
    case 1: return deployment_stage;
    case 2: return from_version;
    case 3: return to_version;
    case 4: return deployment_strategy;
    case 5: return rollback_reason;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deployment_id = value$ != null ? value$.toString() : null; break;
    case 1: deployment_stage = (com.tbw.security.securityevents.DeploymentStage)value$; break;
    case 2: from_version = value$ != null ? value$.toString() : null; break;
    case 3: to_version = value$ != null ? value$.toString() : null; break;
    case 4: deployment_strategy = (com.tbw.security.securityevents.DeploymentStrategy)value$; break;
    case 5: rollback_reason = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deployment_id' field.
   * @return Unique identifier for this deployment
   */
  public java.lang.String getDeploymentId() {
    return deployment_id;
  }


  /**
   * Sets the value of the 'deployment_id' field.
   * Unique identifier for this deployment
   * @param value the value to set.
   */
  public void setDeploymentId(java.lang.String value) {
    this.deployment_id = value;
  }

  /**
   * Gets the value of the 'deployment_stage' field.
   * @return Current stage of deployment
   */
  public com.tbw.security.securityevents.DeploymentStage getDeploymentStage() {
    return deployment_stage;
  }


  /**
   * Sets the value of the 'deployment_stage' field.
   * Current stage of deployment
   * @param value the value to set.
   */
  public void setDeploymentStage(com.tbw.security.securityevents.DeploymentStage value) {
    this.deployment_stage = value;
  }

  /**
   * Gets the value of the 'from_version' field.
   * @return Version being replaced (null for initial deployment)
   */
  public java.lang.String getFromVersion() {
    return from_version;
  }


  /**
   * Sets the value of the 'from_version' field.
   * Version being replaced (null for initial deployment)
   * @param value the value to set.
   */
  public void setFromVersion(java.lang.String value) {
    this.from_version = value;
  }

  /**
   * Gets the value of the 'to_version' field.
   * @return Version being deployed
   */
  public java.lang.String getToVersion() {
    return to_version;
  }


  /**
   * Sets the value of the 'to_version' field.
   * Version being deployed
   * @param value the value to set.
   */
  public void setToVersion(java.lang.String value) {
    this.to_version = value;
  }

  /**
   * Gets the value of the 'deployment_strategy' field.
   * @return Deployment strategy used
   */
  public com.tbw.security.securityevents.DeploymentStrategy getDeploymentStrategy() {
    return deployment_strategy;
  }


  /**
   * Sets the value of the 'deployment_strategy' field.
   * Deployment strategy used
   * @param value the value to set.
   */
  public void setDeploymentStrategy(com.tbw.security.securityevents.DeploymentStrategy value) {
    this.deployment_strategy = value;
  }

  /**
   * Gets the value of the 'rollback_reason' field.
   * @return Reason for rollback if applicable
   */
  public java.lang.String getRollbackReason() {
    return rollback_reason;
  }


  /**
   * Sets the value of the 'rollback_reason' field.
   * Reason for rollback if applicable
   * @param value the value to set.
   */
  public void setRollbackReason(java.lang.String value) {
    this.rollback_reason = value;
  }

  /**
   * Creates a new DeploymentEvent RecordBuilder.
   * @return A new DeploymentEvent RecordBuilder
   */
  public static com.tbw.security.securityevents.DeploymentEvent.Builder newBuilder() {
    return new com.tbw.security.securityevents.DeploymentEvent.Builder();
  }

  /**
   * Creates a new DeploymentEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeploymentEvent RecordBuilder
   */
  public static com.tbw.security.securityevents.DeploymentEvent.Builder newBuilder(com.tbw.security.securityevents.DeploymentEvent.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.DeploymentEvent.Builder();
    } else {
      return new com.tbw.security.securityevents.DeploymentEvent.Builder(other);
    }
  }

  /**
   * Creates a new DeploymentEvent RecordBuilder by copying an existing DeploymentEvent instance.
   * @param other The existing instance to copy.
   * @return A new DeploymentEvent RecordBuilder
   */
  public static com.tbw.security.securityevents.DeploymentEvent.Builder newBuilder(com.tbw.security.securityevents.DeploymentEvent other) {
    if (other == null) {
      return new com.tbw.security.securityevents.DeploymentEvent.Builder();
    } else {
      return new com.tbw.security.securityevents.DeploymentEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeploymentEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeploymentEvent>
    implements org.apache.avro.data.RecordBuilder<DeploymentEvent> {

    /** Unique identifier for this deployment */
    private java.lang.String deployment_id;
    /** Current stage of deployment */
    private com.tbw.security.securityevents.DeploymentStage deployment_stage;
    /** Version being replaced (null for initial deployment) */
    private java.lang.String from_version;
    /** Version being deployed */
    private java.lang.String to_version;
    /** Deployment strategy used */
    private com.tbw.security.securityevents.DeploymentStrategy deployment_strategy;
    /** Reason for rollback if applicable */
    private java.lang.String rollback_reason;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.DeploymentEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deployment_id)) {
        this.deployment_id = data().deepCopy(fields()[0].schema(), other.deployment_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.deployment_stage)) {
        this.deployment_stage = data().deepCopy(fields()[1].schema(), other.deployment_stage);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.from_version)) {
        this.from_version = data().deepCopy(fields()[2].schema(), other.from_version);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.to_version)) {
        this.to_version = data().deepCopy(fields()[3].schema(), other.to_version);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.deployment_strategy)) {
        this.deployment_strategy = data().deepCopy(fields()[4].schema(), other.deployment_strategy);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.rollback_reason)) {
        this.rollback_reason = data().deepCopy(fields()[5].schema(), other.rollback_reason);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing DeploymentEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.DeploymentEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.deployment_id)) {
        this.deployment_id = data().deepCopy(fields()[0].schema(), other.deployment_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.deployment_stage)) {
        this.deployment_stage = data().deepCopy(fields()[1].schema(), other.deployment_stage);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.from_version)) {
        this.from_version = data().deepCopy(fields()[2].schema(), other.from_version);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.to_version)) {
        this.to_version = data().deepCopy(fields()[3].schema(), other.to_version);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.deployment_strategy)) {
        this.deployment_strategy = data().deepCopy(fields()[4].schema(), other.deployment_strategy);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.rollback_reason)) {
        this.rollback_reason = data().deepCopy(fields()[5].schema(), other.rollback_reason);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'deployment_id' field.
      * Unique identifier for this deployment
      * @return The value.
      */
    public java.lang.String getDeploymentId() {
      return deployment_id;
    }


    /**
      * Sets the value of the 'deployment_id' field.
      * Unique identifier for this deployment
      * @param value The value of 'deployment_id'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder setDeploymentId(java.lang.String value) {
      validate(fields()[0], value);
      this.deployment_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deployment_id' field has been set.
      * Unique identifier for this deployment
      * @return True if the 'deployment_id' field has been set, false otherwise.
      */
    public boolean hasDeploymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deployment_id' field.
      * Unique identifier for this deployment
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder clearDeploymentId() {
      deployment_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'deployment_stage' field.
      * Current stage of deployment
      * @return The value.
      */
    public com.tbw.security.securityevents.DeploymentStage getDeploymentStage() {
      return deployment_stage;
    }


    /**
      * Sets the value of the 'deployment_stage' field.
      * Current stage of deployment
      * @param value The value of 'deployment_stage'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder setDeploymentStage(com.tbw.security.securityevents.DeploymentStage value) {
      validate(fields()[1], value);
      this.deployment_stage = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'deployment_stage' field has been set.
      * Current stage of deployment
      * @return True if the 'deployment_stage' field has been set, false otherwise.
      */
    public boolean hasDeploymentStage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'deployment_stage' field.
      * Current stage of deployment
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder clearDeploymentStage() {
      deployment_stage = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'from_version' field.
      * Version being replaced (null for initial deployment)
      * @return The value.
      */
    public java.lang.String getFromVersion() {
      return from_version;
    }


    /**
      * Sets the value of the 'from_version' field.
      * Version being replaced (null for initial deployment)
      * @param value The value of 'from_version'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder setFromVersion(java.lang.String value) {
      validate(fields()[2], value);
      this.from_version = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'from_version' field has been set.
      * Version being replaced (null for initial deployment)
      * @return True if the 'from_version' field has been set, false otherwise.
      */
    public boolean hasFromVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'from_version' field.
      * Version being replaced (null for initial deployment)
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder clearFromVersion() {
      from_version = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'to_version' field.
      * Version being deployed
      * @return The value.
      */
    public java.lang.String getToVersion() {
      return to_version;
    }


    /**
      * Sets the value of the 'to_version' field.
      * Version being deployed
      * @param value The value of 'to_version'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder setToVersion(java.lang.String value) {
      validate(fields()[3], value);
      this.to_version = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'to_version' field has been set.
      * Version being deployed
      * @return True if the 'to_version' field has been set, false otherwise.
      */
    public boolean hasToVersion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'to_version' field.
      * Version being deployed
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder clearToVersion() {
      to_version = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'deployment_strategy' field.
      * Deployment strategy used
      * @return The value.
      */
    public com.tbw.security.securityevents.DeploymentStrategy getDeploymentStrategy() {
      return deployment_strategy;
    }


    /**
      * Sets the value of the 'deployment_strategy' field.
      * Deployment strategy used
      * @param value The value of 'deployment_strategy'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder setDeploymentStrategy(com.tbw.security.securityevents.DeploymentStrategy value) {
      validate(fields()[4], value);
      this.deployment_strategy = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'deployment_strategy' field has been set.
      * Deployment strategy used
      * @return True if the 'deployment_strategy' field has been set, false otherwise.
      */
    public boolean hasDeploymentStrategy() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'deployment_strategy' field.
      * Deployment strategy used
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder clearDeploymentStrategy() {
      deployment_strategy = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'rollback_reason' field.
      * Reason for rollback if applicable
      * @return The value.
      */
    public java.lang.String getRollbackReason() {
      return rollback_reason;
    }


    /**
      * Sets the value of the 'rollback_reason' field.
      * Reason for rollback if applicable
      * @param value The value of 'rollback_reason'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder setRollbackReason(java.lang.String value) {
      validate(fields()[5], value);
      this.rollback_reason = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'rollback_reason' field has been set.
      * Reason for rollback if applicable
      * @return True if the 'rollback_reason' field has been set, false otherwise.
      */
    public boolean hasRollbackReason() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'rollback_reason' field.
      * Reason for rollback if applicable
      * @return This builder.
      */
    public com.tbw.security.securityevents.DeploymentEvent.Builder clearRollbackReason() {
      rollback_reason = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeploymentEvent build() {
      try {
        DeploymentEvent record = new DeploymentEvent();
        record.deployment_id = fieldSetFlags()[0] ? this.deployment_id : (java.lang.String) defaultValue(fields()[0]);
        record.deployment_stage = fieldSetFlags()[1] ? this.deployment_stage : (com.tbw.security.securityevents.DeploymentStage) defaultValue(fields()[1]);
        record.from_version = fieldSetFlags()[2] ? this.from_version : (java.lang.String) defaultValue(fields()[2]);
        record.to_version = fieldSetFlags()[3] ? this.to_version : (java.lang.String) defaultValue(fields()[3]);
        record.deployment_strategy = fieldSetFlags()[4] ? this.deployment_strategy : (com.tbw.security.securityevents.DeploymentStrategy) defaultValue(fields()[4]);
        record.rollback_reason = fieldSetFlags()[5] ? this.rollback_reason : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeploymentEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeploymentEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeploymentEvent>
    READER$ = (org.apache.avro.io.DatumReader<DeploymentEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.deployment_id);

    out.writeEnum(this.deployment_stage.ordinal());

    if (this.from_version == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.from_version);
    }

    out.writeString(this.to_version);

    out.writeEnum(this.deployment_strategy.ordinal());

    if (this.rollback_reason == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.rollback_reason);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.deployment_id = in.readString();

      this.deployment_stage = com.tbw.security.securityevents.DeploymentStage.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.from_version = null;
      } else {
        this.from_version = in.readString();
      }

      this.to_version = in.readString();

      this.deployment_strategy = com.tbw.security.securityevents.DeploymentStrategy.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.rollback_reason = null;
      } else {
        this.rollback_reason = in.readString();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.deployment_id = in.readString();
          break;

        case 1:
          this.deployment_stage = com.tbw.security.securityevents.DeploymentStage.values()[in.readEnum()];
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.from_version = null;
          } else {
            this.from_version = in.readString();
          }
          break;

        case 3:
          this.to_version = in.readString();
          break;

        case 4:
          this.deployment_strategy = com.tbw.security.securityevents.DeploymentStrategy.values()[in.readEnum()];
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.rollback_reason = null;
          } else {
            this.rollback_reason = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










