/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum DeploymentStrategy implements org.apache.avro.generic.GenericEnumSymbol<DeploymentStrategy> {
  BLUE_GREEN, ROLLING, CANARY, RECREATE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DeploymentStrategy\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"BLUE_GREEN\",\"ROLLING\",\"CANARY\",\"RECREATE\"],\"default\":\"ROLLING\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
