/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum Environment implements org.apache.avro.generic.GenericEnumSymbol<Environment> {
  DEVELOPMENT, TESTING, STAGING, PRODUCTION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Environment\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"DEVELOPMENT\",\"TESTING\",\"STAGING\",\"PRODUCTION\"],\"default\":\"DEVELOPMENT\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
