/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum OperationStatus implements org.apache.avro.generic.GenericEnumSymbol<OperationStatus> {
  STARTED, IN_PROGRESS, COMPLETED, FAILED, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OperationStatus\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"STARTED\",\"IN_PROGRESS\",\"COMPLETED\",\"FAILED\",\"CANCELLED\"],\"default\":\"STARTED\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
