/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired when performance thresholds are breached */
@org.apache.avro.specific.AvroGenerated
public class PerformanceAlert extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7146791811334845753L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PerformanceAlert\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired when performance thresholds are breached\",\"fields\":[{\"name\":\"metric_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the performance metric\"},{\"name\":\"current_value\",\"type\":\"double\",\"doc\":\"Current value of the metric\"},{\"name\":\"threshold_value\",\"type\":\"double\",\"doc\":\"Threshold that was breached\"},{\"name\":\"alert_type\",\"type\":{\"type\":\"enum\",\"name\":\"AlertType\",\"symbols\":[\"THRESHOLD_EXCEEDED\",\"THRESHOLD_RECOVERED\",\"ANOMALY_DETECTED\"],\"default\":\"THRESHOLD_EXCEEDED\"},\"doc\":\"Type of performance alert\"},{\"name\":\"measurement_unit\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')\",\"default\":\"count\"},{\"name\":\"duration_seconds\",\"type\":[\"null\",\"long\"],\"doc\":\"How long the condition has persisted\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PerformanceAlert> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PerformanceAlert> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PerformanceAlert> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PerformanceAlert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PerformanceAlert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PerformanceAlert to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PerformanceAlert from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PerformanceAlert instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PerformanceAlert fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of the performance metric */
  private java.lang.String metric_name;
  /** Current value of the metric */
  private double current_value;
  /** Threshold that was breached */
  private double threshold_value;
  /** Type of performance alert */
  private com.tbw.security.securityevents.AlertType alert_type;
  /** Unit of measurement (e.g., 'ms', 'MB', 'requests/sec') */
  private java.lang.String measurement_unit;
  /** How long the condition has persisted */
  private java.lang.Long duration_seconds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PerformanceAlert() {}

  /**
   * All-args constructor.
   * @param metric_name Name of the performance metric
   * @param current_value Current value of the metric
   * @param threshold_value Threshold that was breached
   * @param alert_type Type of performance alert
   * @param measurement_unit Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')
   * @param duration_seconds How long the condition has persisted
   */
  public PerformanceAlert(java.lang.String metric_name, java.lang.Double current_value, java.lang.Double threshold_value, com.tbw.security.securityevents.AlertType alert_type, java.lang.String measurement_unit, java.lang.Long duration_seconds) {
    this.metric_name = metric_name;
    this.current_value = current_value;
    this.threshold_value = threshold_value;
    this.alert_type = alert_type;
    this.measurement_unit = measurement_unit;
    this.duration_seconds = duration_seconds;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return metric_name;
    case 1: return current_value;
    case 2: return threshold_value;
    case 3: return alert_type;
    case 4: return measurement_unit;
    case 5: return duration_seconds;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: metric_name = value$ != null ? value$.toString() : null; break;
    case 1: current_value = (java.lang.Double)value$; break;
    case 2: threshold_value = (java.lang.Double)value$; break;
    case 3: alert_type = (com.tbw.security.securityevents.AlertType)value$; break;
    case 4: measurement_unit = value$ != null ? value$.toString() : null; break;
    case 5: duration_seconds = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'metric_name' field.
   * @return Name of the performance metric
   */
  public java.lang.String getMetricName() {
    return metric_name;
  }


  /**
   * Sets the value of the 'metric_name' field.
   * Name of the performance metric
   * @param value the value to set.
   */
  public void setMetricName(java.lang.String value) {
    this.metric_name = value;
  }

  /**
   * Gets the value of the 'current_value' field.
   * @return Current value of the metric
   */
  public double getCurrentValue() {
    return current_value;
  }


  /**
   * Sets the value of the 'current_value' field.
   * Current value of the metric
   * @param value the value to set.
   */
  public void setCurrentValue(double value) {
    this.current_value = value;
  }

  /**
   * Gets the value of the 'threshold_value' field.
   * @return Threshold that was breached
   */
  public double getThresholdValue() {
    return threshold_value;
  }


  /**
   * Sets the value of the 'threshold_value' field.
   * Threshold that was breached
   * @param value the value to set.
   */
  public void setThresholdValue(double value) {
    this.threshold_value = value;
  }

  /**
   * Gets the value of the 'alert_type' field.
   * @return Type of performance alert
   */
  public com.tbw.security.securityevents.AlertType getAlertType() {
    return alert_type;
  }


  /**
   * Sets the value of the 'alert_type' field.
   * Type of performance alert
   * @param value the value to set.
   */
  public void setAlertType(com.tbw.security.securityevents.AlertType value) {
    this.alert_type = value;
  }

  /**
   * Gets the value of the 'measurement_unit' field.
   * @return Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')
   */
  public java.lang.String getMeasurementUnit() {
    return measurement_unit;
  }


  /**
   * Sets the value of the 'measurement_unit' field.
   * Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')
   * @param value the value to set.
   */
  public void setMeasurementUnit(java.lang.String value) {
    this.measurement_unit = value;
  }

  /**
   * Gets the value of the 'duration_seconds' field.
   * @return How long the condition has persisted
   */
  public java.lang.Long getDurationSeconds() {
    return duration_seconds;
  }


  /**
   * Sets the value of the 'duration_seconds' field.
   * How long the condition has persisted
   * @param value the value to set.
   */
  public void setDurationSeconds(java.lang.Long value) {
    this.duration_seconds = value;
  }

  /**
   * Creates a new PerformanceAlert RecordBuilder.
   * @return A new PerformanceAlert RecordBuilder
   */
  public static com.tbw.security.securityevents.PerformanceAlert.Builder newBuilder() {
    return new com.tbw.security.securityevents.PerformanceAlert.Builder();
  }

  /**
   * Creates a new PerformanceAlert RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PerformanceAlert RecordBuilder
   */
  public static com.tbw.security.securityevents.PerformanceAlert.Builder newBuilder(com.tbw.security.securityevents.PerformanceAlert.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.PerformanceAlert.Builder();
    } else {
      return new com.tbw.security.securityevents.PerformanceAlert.Builder(other);
    }
  }

  /**
   * Creates a new PerformanceAlert RecordBuilder by copying an existing PerformanceAlert instance.
   * @param other The existing instance to copy.
   * @return A new PerformanceAlert RecordBuilder
   */
  public static com.tbw.security.securityevents.PerformanceAlert.Builder newBuilder(com.tbw.security.securityevents.PerformanceAlert other) {
    if (other == null) {
      return new com.tbw.security.securityevents.PerformanceAlert.Builder();
    } else {
      return new com.tbw.security.securityevents.PerformanceAlert.Builder(other);
    }
  }

  /**
   * RecordBuilder for PerformanceAlert instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PerformanceAlert>
    implements org.apache.avro.data.RecordBuilder<PerformanceAlert> {

    /** Name of the performance metric */
    private java.lang.String metric_name;
    /** Current value of the metric */
    private double current_value;
    /** Threshold that was breached */
    private double threshold_value;
    /** Type of performance alert */
    private com.tbw.security.securityevents.AlertType alert_type;
    /** Unit of measurement (e.g., 'ms', 'MB', 'requests/sec') */
    private java.lang.String measurement_unit;
    /** How long the condition has persisted */
    private java.lang.Long duration_seconds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.PerformanceAlert.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.metric_name)) {
        this.metric_name = data().deepCopy(fields()[0].schema(), other.metric_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.current_value)) {
        this.current_value = data().deepCopy(fields()[1].schema(), other.current_value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.threshold_value)) {
        this.threshold_value = data().deepCopy(fields()[2].schema(), other.threshold_value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.alert_type)) {
        this.alert_type = data().deepCopy(fields()[3].schema(), other.alert_type);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.measurement_unit)) {
        this.measurement_unit = data().deepCopy(fields()[4].schema(), other.measurement_unit);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.duration_seconds)) {
        this.duration_seconds = data().deepCopy(fields()[5].schema(), other.duration_seconds);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing PerformanceAlert instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.PerformanceAlert other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.metric_name)) {
        this.metric_name = data().deepCopy(fields()[0].schema(), other.metric_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.current_value)) {
        this.current_value = data().deepCopy(fields()[1].schema(), other.current_value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.threshold_value)) {
        this.threshold_value = data().deepCopy(fields()[2].schema(), other.threshold_value);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.alert_type)) {
        this.alert_type = data().deepCopy(fields()[3].schema(), other.alert_type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.measurement_unit)) {
        this.measurement_unit = data().deepCopy(fields()[4].schema(), other.measurement_unit);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.duration_seconds)) {
        this.duration_seconds = data().deepCopy(fields()[5].schema(), other.duration_seconds);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'metric_name' field.
      * Name of the performance metric
      * @return The value.
      */
    public java.lang.String getMetricName() {
      return metric_name;
    }


    /**
      * Sets the value of the 'metric_name' field.
      * Name of the performance metric
      * @param value The value of 'metric_name'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder setMetricName(java.lang.String value) {
      validate(fields()[0], value);
      this.metric_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'metric_name' field has been set.
      * Name of the performance metric
      * @return True if the 'metric_name' field has been set, false otherwise.
      */
    public boolean hasMetricName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'metric_name' field.
      * Name of the performance metric
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder clearMetricName() {
      metric_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'current_value' field.
      * Current value of the metric
      * @return The value.
      */
    public double getCurrentValue() {
      return current_value;
    }


    /**
      * Sets the value of the 'current_value' field.
      * Current value of the metric
      * @param value The value of 'current_value'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder setCurrentValue(double value) {
      validate(fields()[1], value);
      this.current_value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'current_value' field has been set.
      * Current value of the metric
      * @return True if the 'current_value' field has been set, false otherwise.
      */
    public boolean hasCurrentValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'current_value' field.
      * Current value of the metric
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder clearCurrentValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'threshold_value' field.
      * Threshold that was breached
      * @return The value.
      */
    public double getThresholdValue() {
      return threshold_value;
    }


    /**
      * Sets the value of the 'threshold_value' field.
      * Threshold that was breached
      * @param value The value of 'threshold_value'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder setThresholdValue(double value) {
      validate(fields()[2], value);
      this.threshold_value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'threshold_value' field has been set.
      * Threshold that was breached
      * @return True if the 'threshold_value' field has been set, false otherwise.
      */
    public boolean hasThresholdValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'threshold_value' field.
      * Threshold that was breached
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder clearThresholdValue() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_type' field.
      * Type of performance alert
      * @return The value.
      */
    public com.tbw.security.securityevents.AlertType getAlertType() {
      return alert_type;
    }


    /**
      * Sets the value of the 'alert_type' field.
      * Type of performance alert
      * @param value The value of 'alert_type'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder setAlertType(com.tbw.security.securityevents.AlertType value) {
      validate(fields()[3], value);
      this.alert_type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_type' field has been set.
      * Type of performance alert
      * @return True if the 'alert_type' field has been set, false otherwise.
      */
    public boolean hasAlertType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'alert_type' field.
      * Type of performance alert
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder clearAlertType() {
      alert_type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'measurement_unit' field.
      * Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')
      * @return The value.
      */
    public java.lang.String getMeasurementUnit() {
      return measurement_unit;
    }


    /**
      * Sets the value of the 'measurement_unit' field.
      * Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')
      * @param value The value of 'measurement_unit'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder setMeasurementUnit(java.lang.String value) {
      validate(fields()[4], value);
      this.measurement_unit = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'measurement_unit' field has been set.
      * Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')
      * @return True if the 'measurement_unit' field has been set, false otherwise.
      */
    public boolean hasMeasurementUnit() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'measurement_unit' field.
      * Unit of measurement (e.g., 'ms', 'MB', 'requests/sec')
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder clearMeasurementUnit() {
      measurement_unit = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration_seconds' field.
      * How long the condition has persisted
      * @return The value.
      */
    public java.lang.Long getDurationSeconds() {
      return duration_seconds;
    }


    /**
      * Sets the value of the 'duration_seconds' field.
      * How long the condition has persisted
      * @param value The value of 'duration_seconds'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder setDurationSeconds(java.lang.Long value) {
      validate(fields()[5], value);
      this.duration_seconds = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'duration_seconds' field has been set.
      * How long the condition has persisted
      * @return True if the 'duration_seconds' field has been set, false otherwise.
      */
    public boolean hasDurationSeconds() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'duration_seconds' field.
      * How long the condition has persisted
      * @return This builder.
      */
    public com.tbw.security.securityevents.PerformanceAlert.Builder clearDurationSeconds() {
      duration_seconds = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PerformanceAlert build() {
      try {
        PerformanceAlert record = new PerformanceAlert();
        record.metric_name = fieldSetFlags()[0] ? this.metric_name : (java.lang.String) defaultValue(fields()[0]);
        record.current_value = fieldSetFlags()[1] ? this.current_value : (java.lang.Double) defaultValue(fields()[1]);
        record.threshold_value = fieldSetFlags()[2] ? this.threshold_value : (java.lang.Double) defaultValue(fields()[2]);
        record.alert_type = fieldSetFlags()[3] ? this.alert_type : (com.tbw.security.securityevents.AlertType) defaultValue(fields()[3]);
        record.measurement_unit = fieldSetFlags()[4] ? this.measurement_unit : (java.lang.String) defaultValue(fields()[4]);
        record.duration_seconds = fieldSetFlags()[5] ? this.duration_seconds : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PerformanceAlert>
    WRITER$ = (org.apache.avro.io.DatumWriter<PerformanceAlert>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PerformanceAlert>
    READER$ = (org.apache.avro.io.DatumReader<PerformanceAlert>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.metric_name);

    out.writeDouble(this.current_value);

    out.writeDouble(this.threshold_value);

    out.writeEnum(this.alert_type.ordinal());

    out.writeString(this.measurement_unit);

    if (this.duration_seconds == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.duration_seconds);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.metric_name = in.readString();

      this.current_value = in.readDouble();

      this.threshold_value = in.readDouble();

      this.alert_type = com.tbw.security.securityevents.AlertType.values()[in.readEnum()];

      this.measurement_unit = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.duration_seconds = null;
      } else {
        this.duration_seconds = in.readLong();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.metric_name = in.readString();
          break;

        case 1:
          this.current_value = in.readDouble();
          break;

        case 2:
          this.threshold_value = in.readDouble();
          break;

        case 3:
          this.alert_type = com.tbw.security.securityevents.AlertType.values()[in.readEnum()];
          break;

        case 4:
          this.measurement_unit = in.readString();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.duration_seconds = null;
          } else {
            this.duration_seconds = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










