/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum SecurityEventType implements org.apache.avro.generic.GenericEnumSymbol<SecurityEventType> {
  AUTHENTICATION_FAILURE, AUTHORIZATION_FAILURE, CERTIFICATE_EXPIRY_WARNING, CERTIFICATE_RENEWED, API_KEY_ROTATED, SUSPICIOUS_ACTIVITY, SECURITY_SCAN_COMPLETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SecurityEventType\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"AUTHENTICATION_FAILURE\",\"AUTHORIZATION_FAILURE\",\"CERTIFICATE_EXPIRY_WARNING\",\"CERTIFICATE_RENEWED\",\"API_KEY_ROTATED\",\"SUSPICIOUS_ACTIVITY\",\"SECURITY_SCAN_COMPLETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
