/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired for security-related lifecycle events */
@org.apache.avro.specific.AvroGenerated
public class SecurityEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8540655392862118908L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SecurityEvent\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired for security-related lifecycle events\",\"fields\":[{\"name\":\"event_type\",\"type\":{\"type\":\"enum\",\"name\":\"SecurityEventType\",\"symbols\":[\"AUTHENTICATION_FAILURE\",\"AUTHORIZATION_FAILURE\",\"CERTIFICATE_EXPIRY_WARNING\",\"CERTIFICATE_RENEWED\",\"API_KEY_ROTATED\",\"SUSPICIOUS_ACTIVITY\",\"SECURITY_SCAN_COMPLETED\"]},\"doc\":\"Type of security event\"},{\"name\":\"resource\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Resource or endpoint involved in the security event\",\"default\":null},{\"name\":\"threat_level\",\"type\":{\"type\":\"enum\",\"name\":\"ThreatLevel\",\"symbols\":[\"LOW\",\"MEDIUM\",\"HIGH\",\"CRITICAL\"],\"default\":\"LOW\"},\"doc\":\"Assessed threat level of the event\"},{\"name\":\"client_ip\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"IP address of the client involved\",\"default\":null},{\"name\":\"user_agent\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"User agent string if applicable\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SecurityEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SecurityEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SecurityEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SecurityEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SecurityEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SecurityEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SecurityEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SecurityEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SecurityEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Type of security event */
  private com.tbw.security.securityevents.SecurityEventType event_type;
  /** Resource or endpoint involved in the security event */
  private java.lang.String resource;
  /** Assessed threat level of the event */
  private com.tbw.security.securityevents.ThreatLevel threat_level;
  /** IP address of the client involved */
  private java.lang.String client_ip;
  /** User agent string if applicable */
  private java.lang.String user_agent;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SecurityEvent() {}

  /**
   * All-args constructor.
   * @param event_type Type of security event
   * @param resource Resource or endpoint involved in the security event
   * @param threat_level Assessed threat level of the event
   * @param client_ip IP address of the client involved
   * @param user_agent User agent string if applicable
   */
  public SecurityEvent(com.tbw.security.securityevents.SecurityEventType event_type, java.lang.String resource, com.tbw.security.securityevents.ThreatLevel threat_level, java.lang.String client_ip, java.lang.String user_agent) {
    this.event_type = event_type;
    this.resource = resource;
    this.threat_level = threat_level;
    this.client_ip = client_ip;
    this.user_agent = user_agent;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return event_type;
    case 1: return resource;
    case 2: return threat_level;
    case 3: return client_ip;
    case 4: return user_agent;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: event_type = (com.tbw.security.securityevents.SecurityEventType)value$; break;
    case 1: resource = value$ != null ? value$.toString() : null; break;
    case 2: threat_level = (com.tbw.security.securityevents.ThreatLevel)value$; break;
    case 3: client_ip = value$ != null ? value$.toString() : null; break;
    case 4: user_agent = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'event_type' field.
   * @return Type of security event
   */
  public com.tbw.security.securityevents.SecurityEventType getEventType() {
    return event_type;
  }


  /**
   * Sets the value of the 'event_type' field.
   * Type of security event
   * @param value the value to set.
   */
  public void setEventType(com.tbw.security.securityevents.SecurityEventType value) {
    this.event_type = value;
  }

  /**
   * Gets the value of the 'resource' field.
   * @return Resource or endpoint involved in the security event
   */
  public java.lang.String getResource() {
    return resource;
  }


  /**
   * Sets the value of the 'resource' field.
   * Resource or endpoint involved in the security event
   * @param value the value to set.
   */
  public void setResource(java.lang.String value) {
    this.resource = value;
  }

  /**
   * Gets the value of the 'threat_level' field.
   * @return Assessed threat level of the event
   */
  public com.tbw.security.securityevents.ThreatLevel getThreatLevel() {
    return threat_level;
  }


  /**
   * Sets the value of the 'threat_level' field.
   * Assessed threat level of the event
   * @param value the value to set.
   */
  public void setThreatLevel(com.tbw.security.securityevents.ThreatLevel value) {
    this.threat_level = value;
  }

  /**
   * Gets the value of the 'client_ip' field.
   * @return IP address of the client involved
   */
  public java.lang.String getClientIp() {
    return client_ip;
  }


  /**
   * Sets the value of the 'client_ip' field.
   * IP address of the client involved
   * @param value the value to set.
   */
  public void setClientIp(java.lang.String value) {
    this.client_ip = value;
  }

  /**
   * Gets the value of the 'user_agent' field.
   * @return User agent string if applicable
   */
  public java.lang.String getUserAgent() {
    return user_agent;
  }


  /**
   * Sets the value of the 'user_agent' field.
   * User agent string if applicable
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.String value) {
    this.user_agent = value;
  }

  /**
   * Creates a new SecurityEvent RecordBuilder.
   * @return A new SecurityEvent RecordBuilder
   */
  public static com.tbw.security.securityevents.SecurityEvent.Builder newBuilder() {
    return new com.tbw.security.securityevents.SecurityEvent.Builder();
  }

  /**
   * Creates a new SecurityEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SecurityEvent RecordBuilder
   */
  public static com.tbw.security.securityevents.SecurityEvent.Builder newBuilder(com.tbw.security.securityevents.SecurityEvent.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.SecurityEvent.Builder();
    } else {
      return new com.tbw.security.securityevents.SecurityEvent.Builder(other);
    }
  }

  /**
   * Creates a new SecurityEvent RecordBuilder by copying an existing SecurityEvent instance.
   * @param other The existing instance to copy.
   * @return A new SecurityEvent RecordBuilder
   */
  public static com.tbw.security.securityevents.SecurityEvent.Builder newBuilder(com.tbw.security.securityevents.SecurityEvent other) {
    if (other == null) {
      return new com.tbw.security.securityevents.SecurityEvent.Builder();
    } else {
      return new com.tbw.security.securityevents.SecurityEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for SecurityEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SecurityEvent>
    implements org.apache.avro.data.RecordBuilder<SecurityEvent> {

    /** Type of security event */
    private com.tbw.security.securityevents.SecurityEventType event_type;
    /** Resource or endpoint involved in the security event */
    private java.lang.String resource;
    /** Assessed threat level of the event */
    private com.tbw.security.securityevents.ThreatLevel threat_level;
    /** IP address of the client involved */
    private java.lang.String client_ip;
    /** User agent string if applicable */
    private java.lang.String user_agent;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.SecurityEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.event_type)) {
        this.event_type = data().deepCopy(fields()[0].schema(), other.event_type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.resource)) {
        this.resource = data().deepCopy(fields()[1].schema(), other.resource);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.threat_level)) {
        this.threat_level = data().deepCopy(fields()[2].schema(), other.threat_level);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.client_ip)) {
        this.client_ip = data().deepCopy(fields()[3].schema(), other.client_ip);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.user_agent)) {
        this.user_agent = data().deepCopy(fields()[4].schema(), other.user_agent);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing SecurityEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.SecurityEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.event_type)) {
        this.event_type = data().deepCopy(fields()[0].schema(), other.event_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.resource)) {
        this.resource = data().deepCopy(fields()[1].schema(), other.resource);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.threat_level)) {
        this.threat_level = data().deepCopy(fields()[2].schema(), other.threat_level);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.client_ip)) {
        this.client_ip = data().deepCopy(fields()[3].schema(), other.client_ip);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.user_agent)) {
        this.user_agent = data().deepCopy(fields()[4].schema(), other.user_agent);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'event_type' field.
      * Type of security event
      * @return The value.
      */
    public com.tbw.security.securityevents.SecurityEventType getEventType() {
      return event_type;
    }


    /**
      * Sets the value of the 'event_type' field.
      * Type of security event
      * @param value The value of 'event_type'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder setEventType(com.tbw.security.securityevents.SecurityEventType value) {
      validate(fields()[0], value);
      this.event_type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'event_type' field has been set.
      * Type of security event
      * @return True if the 'event_type' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'event_type' field.
      * Type of security event
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder clearEventType() {
      event_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'resource' field.
      * Resource or endpoint involved in the security event
      * @return The value.
      */
    public java.lang.String getResource() {
      return resource;
    }


    /**
      * Sets the value of the 'resource' field.
      * Resource or endpoint involved in the security event
      * @param value The value of 'resource'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder setResource(java.lang.String value) {
      validate(fields()[1], value);
      this.resource = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'resource' field has been set.
      * Resource or endpoint involved in the security event
      * @return True if the 'resource' field has been set, false otherwise.
      */
    public boolean hasResource() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'resource' field.
      * Resource or endpoint involved in the security event
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder clearResource() {
      resource = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'threat_level' field.
      * Assessed threat level of the event
      * @return The value.
      */
    public com.tbw.security.securityevents.ThreatLevel getThreatLevel() {
      return threat_level;
    }


    /**
      * Sets the value of the 'threat_level' field.
      * Assessed threat level of the event
      * @param value The value of 'threat_level'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder setThreatLevel(com.tbw.security.securityevents.ThreatLevel value) {
      validate(fields()[2], value);
      this.threat_level = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'threat_level' field has been set.
      * Assessed threat level of the event
      * @return True if the 'threat_level' field has been set, false otherwise.
      */
    public boolean hasThreatLevel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'threat_level' field.
      * Assessed threat level of the event
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder clearThreatLevel() {
      threat_level = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'client_ip' field.
      * IP address of the client involved
      * @return The value.
      */
    public java.lang.String getClientIp() {
      return client_ip;
    }


    /**
      * Sets the value of the 'client_ip' field.
      * IP address of the client involved
      * @param value The value of 'client_ip'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder setClientIp(java.lang.String value) {
      validate(fields()[3], value);
      this.client_ip = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'client_ip' field has been set.
      * IP address of the client involved
      * @return True if the 'client_ip' field has been set, false otherwise.
      */
    public boolean hasClientIp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'client_ip' field.
      * IP address of the client involved
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder clearClientIp() {
      client_ip = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_agent' field.
      * User agent string if applicable
      * @return The value.
      */
    public java.lang.String getUserAgent() {
      return user_agent;
    }


    /**
      * Sets the value of the 'user_agent' field.
      * User agent string if applicable
      * @param value The value of 'user_agent'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder setUserAgent(java.lang.String value) {
      validate(fields()[4], value);
      this.user_agent = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'user_agent' field has been set.
      * User agent string if applicable
      * @return True if the 'user_agent' field has been set, false otherwise.
      */
    public boolean hasUserAgent() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'user_agent' field.
      * User agent string if applicable
      * @return This builder.
      */
    public com.tbw.security.securityevents.SecurityEvent.Builder clearUserAgent() {
      user_agent = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SecurityEvent build() {
      try {
        SecurityEvent record = new SecurityEvent();
        record.event_type = fieldSetFlags()[0] ? this.event_type : (com.tbw.security.securityevents.SecurityEventType) defaultValue(fields()[0]);
        record.resource = fieldSetFlags()[1] ? this.resource : (java.lang.String) defaultValue(fields()[1]);
        record.threat_level = fieldSetFlags()[2] ? this.threat_level : (com.tbw.security.securityevents.ThreatLevel) defaultValue(fields()[2]);
        record.client_ip = fieldSetFlags()[3] ? this.client_ip : (java.lang.String) defaultValue(fields()[3]);
        record.user_agent = fieldSetFlags()[4] ? this.user_agent : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SecurityEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<SecurityEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SecurityEvent>
    READER$ = (org.apache.avro.io.DatumReader<SecurityEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.event_type.ordinal());

    if (this.resource == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.resource);
    }

    out.writeEnum(this.threat_level.ordinal());

    if (this.client_ip == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.client_ip);
    }

    if (this.user_agent == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.user_agent);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.event_type = com.tbw.security.securityevents.SecurityEventType.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.resource = null;
      } else {
        this.resource = in.readString();
      }

      this.threat_level = com.tbw.security.securityevents.ThreatLevel.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.client_ip = null;
      } else {
        this.client_ip = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.user_agent = null;
      } else {
        this.user_agent = in.readString();
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.event_type = com.tbw.security.securityevents.SecurityEventType.values()[in.readEnum()];
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.resource = null;
          } else {
            this.resource = in.readString();
          }
          break;

        case 2:
          this.threat_level = com.tbw.security.securityevents.ThreatLevel.values()[in.readEnum()];
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.client_ip = null;
          } else {
            this.client_ip = in.readString();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.user_agent = null;
          } else {
            this.user_agent = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










