/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event fired when a service or component changes status */
@org.apache.avro.specific.AvroGenerated
public class ServiceStatusChange extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1608519995986014408L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ServiceStatusChange\",\"namespace\":\"com.tbw.security.securityevents\",\"doc\":\"Event fired when a service or component changes status\",\"fields\":[{\"name\":\"service_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the service or component\"},{\"name\":\"previous_status\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"ServiceStatus\",\"symbols\":[\"STARTING\",\"HEALTHY\",\"DEGRADED\",\"UNHEALTHY\",\"STOPPED\",\"UNKNOWN\"]}],\"doc\":\"Previous service status\",\"default\":null},{\"name\":\"current_status\",\"type\":\"ServiceStatus\",\"doc\":\"Current service status\"},{\"name\":\"status_details\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Additional details about the status change\",\"default\":null},{\"name\":\"health_check_url\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"URL used for health checking this service\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ServiceStatusChange> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ServiceStatusChange> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ServiceStatusChange> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ServiceStatusChange> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ServiceStatusChange> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ServiceStatusChange to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ServiceStatusChange from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ServiceStatusChange instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ServiceStatusChange fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of the service or component */
  private java.lang.String service_name;
  /** Previous service status */
  private com.tbw.security.securityevents.ServiceStatus previous_status;
  /** Current service status */
  private com.tbw.security.securityevents.ServiceStatus current_status;
  /** Additional details about the status change */
  private java.lang.String status_details;
  /** URL used for health checking this service */
  private java.lang.String health_check_url;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ServiceStatusChange() {}

  /**
   * All-args constructor.
   * @param service_name Name of the service or component
   * @param previous_status Previous service status
   * @param current_status Current service status
   * @param status_details Additional details about the status change
   * @param health_check_url URL used for health checking this service
   */
  public ServiceStatusChange(java.lang.String service_name, com.tbw.security.securityevents.ServiceStatus previous_status, com.tbw.security.securityevents.ServiceStatus current_status, java.lang.String status_details, java.lang.String health_check_url) {
    this.service_name = service_name;
    this.previous_status = previous_status;
    this.current_status = current_status;
    this.status_details = status_details;
    this.health_check_url = health_check_url;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return service_name;
    case 1: return previous_status;
    case 2: return current_status;
    case 3: return status_details;
    case 4: return health_check_url;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: service_name = value$ != null ? value$.toString() : null; break;
    case 1: previous_status = (com.tbw.security.securityevents.ServiceStatus)value$; break;
    case 2: current_status = (com.tbw.security.securityevents.ServiceStatus)value$; break;
    case 3: status_details = value$ != null ? value$.toString() : null; break;
    case 4: health_check_url = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'service_name' field.
   * @return Name of the service or component
   */
  public java.lang.String getServiceName() {
    return service_name;
  }


  /**
   * Sets the value of the 'service_name' field.
   * Name of the service or component
   * @param value the value to set.
   */
  public void setServiceName(java.lang.String value) {
    this.service_name = value;
  }

  /**
   * Gets the value of the 'previous_status' field.
   * @return Previous service status
   */
  public com.tbw.security.securityevents.ServiceStatus getPreviousStatus() {
    return previous_status;
  }


  /**
   * Sets the value of the 'previous_status' field.
   * Previous service status
   * @param value the value to set.
   */
  public void setPreviousStatus(com.tbw.security.securityevents.ServiceStatus value) {
    this.previous_status = value;
  }

  /**
   * Gets the value of the 'current_status' field.
   * @return Current service status
   */
  public com.tbw.security.securityevents.ServiceStatus getCurrentStatus() {
    return current_status;
  }


  /**
   * Sets the value of the 'current_status' field.
   * Current service status
   * @param value the value to set.
   */
  public void setCurrentStatus(com.tbw.security.securityevents.ServiceStatus value) {
    this.current_status = value;
  }

  /**
   * Gets the value of the 'status_details' field.
   * @return Additional details about the status change
   */
  public java.lang.String getStatusDetails() {
    return status_details;
  }


  /**
   * Sets the value of the 'status_details' field.
   * Additional details about the status change
   * @param value the value to set.
   */
  public void setStatusDetails(java.lang.String value) {
    this.status_details = value;
  }

  /**
   * Gets the value of the 'health_check_url' field.
   * @return URL used for health checking this service
   */
  public java.lang.String getHealthCheckUrl() {
    return health_check_url;
  }


  /**
   * Sets the value of the 'health_check_url' field.
   * URL used for health checking this service
   * @param value the value to set.
   */
  public void setHealthCheckUrl(java.lang.String value) {
    this.health_check_url = value;
  }

  /**
   * Creates a new ServiceStatusChange RecordBuilder.
   * @return A new ServiceStatusChange RecordBuilder
   */
  public static com.tbw.security.securityevents.ServiceStatusChange.Builder newBuilder() {
    return new com.tbw.security.securityevents.ServiceStatusChange.Builder();
  }

  /**
   * Creates a new ServiceStatusChange RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ServiceStatusChange RecordBuilder
   */
  public static com.tbw.security.securityevents.ServiceStatusChange.Builder newBuilder(com.tbw.security.securityevents.ServiceStatusChange.Builder other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ServiceStatusChange.Builder();
    } else {
      return new com.tbw.security.securityevents.ServiceStatusChange.Builder(other);
    }
  }

  /**
   * Creates a new ServiceStatusChange RecordBuilder by copying an existing ServiceStatusChange instance.
   * @param other The existing instance to copy.
   * @return A new ServiceStatusChange RecordBuilder
   */
  public static com.tbw.security.securityevents.ServiceStatusChange.Builder newBuilder(com.tbw.security.securityevents.ServiceStatusChange other) {
    if (other == null) {
      return new com.tbw.security.securityevents.ServiceStatusChange.Builder();
    } else {
      return new com.tbw.security.securityevents.ServiceStatusChange.Builder(other);
    }
  }

  /**
   * RecordBuilder for ServiceStatusChange instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ServiceStatusChange>
    implements org.apache.avro.data.RecordBuilder<ServiceStatusChange> {

    /** Name of the service or component */
    private java.lang.String service_name;
    /** Previous service status */
    private com.tbw.security.securityevents.ServiceStatus previous_status;
    /** Current service status */
    private com.tbw.security.securityevents.ServiceStatus current_status;
    /** Additional details about the status change */
    private java.lang.String status_details;
    /** URL used for health checking this service */
    private java.lang.String health_check_url;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tbw.security.securityevents.ServiceStatusChange.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.service_name)) {
        this.service_name = data().deepCopy(fields()[0].schema(), other.service_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.previous_status)) {
        this.previous_status = data().deepCopy(fields()[1].schema(), other.previous_status);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.current_status)) {
        this.current_status = data().deepCopy(fields()[2].schema(), other.current_status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.status_details)) {
        this.status_details = data().deepCopy(fields()[3].schema(), other.status_details);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.health_check_url)) {
        this.health_check_url = data().deepCopy(fields()[4].schema(), other.health_check_url);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ServiceStatusChange instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tbw.security.securityevents.ServiceStatusChange other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.service_name)) {
        this.service_name = data().deepCopy(fields()[0].schema(), other.service_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.previous_status)) {
        this.previous_status = data().deepCopy(fields()[1].schema(), other.previous_status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.current_status)) {
        this.current_status = data().deepCopy(fields()[2].schema(), other.current_status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status_details)) {
        this.status_details = data().deepCopy(fields()[3].schema(), other.status_details);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.health_check_url)) {
        this.health_check_url = data().deepCopy(fields()[4].schema(), other.health_check_url);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'service_name' field.
      * Name of the service or component
      * @return The value.
      */
    public java.lang.String getServiceName() {
      return service_name;
    }


    /**
      * Sets the value of the 'service_name' field.
      * Name of the service or component
      * @param value The value of 'service_name'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder setServiceName(java.lang.String value) {
      validate(fields()[0], value);
      this.service_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'service_name' field has been set.
      * Name of the service or component
      * @return True if the 'service_name' field has been set, false otherwise.
      */
    public boolean hasServiceName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'service_name' field.
      * Name of the service or component
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder clearServiceName() {
      service_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'previous_status' field.
      * Previous service status
      * @return The value.
      */
    public com.tbw.security.securityevents.ServiceStatus getPreviousStatus() {
      return previous_status;
    }


    /**
      * Sets the value of the 'previous_status' field.
      * Previous service status
      * @param value The value of 'previous_status'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder setPreviousStatus(com.tbw.security.securityevents.ServiceStatus value) {
      validate(fields()[1], value);
      this.previous_status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'previous_status' field has been set.
      * Previous service status
      * @return True if the 'previous_status' field has been set, false otherwise.
      */
    public boolean hasPreviousStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'previous_status' field.
      * Previous service status
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder clearPreviousStatus() {
      previous_status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'current_status' field.
      * Current service status
      * @return The value.
      */
    public com.tbw.security.securityevents.ServiceStatus getCurrentStatus() {
      return current_status;
    }


    /**
      * Sets the value of the 'current_status' field.
      * Current service status
      * @param value The value of 'current_status'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder setCurrentStatus(com.tbw.security.securityevents.ServiceStatus value) {
      validate(fields()[2], value);
      this.current_status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'current_status' field has been set.
      * Current service status
      * @return True if the 'current_status' field has been set, false otherwise.
      */
    public boolean hasCurrentStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'current_status' field.
      * Current service status
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder clearCurrentStatus() {
      current_status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_details' field.
      * Additional details about the status change
      * @return The value.
      */
    public java.lang.String getStatusDetails() {
      return status_details;
    }


    /**
      * Sets the value of the 'status_details' field.
      * Additional details about the status change
      * @param value The value of 'status_details'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder setStatusDetails(java.lang.String value) {
      validate(fields()[3], value);
      this.status_details = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status_details' field has been set.
      * Additional details about the status change
      * @return True if the 'status_details' field has been set, false otherwise.
      */
    public boolean hasStatusDetails() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status_details' field.
      * Additional details about the status change
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder clearStatusDetails() {
      status_details = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'health_check_url' field.
      * URL used for health checking this service
      * @return The value.
      */
    public java.lang.String getHealthCheckUrl() {
      return health_check_url;
    }


    /**
      * Sets the value of the 'health_check_url' field.
      * URL used for health checking this service
      * @param value The value of 'health_check_url'.
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder setHealthCheckUrl(java.lang.String value) {
      validate(fields()[4], value);
      this.health_check_url = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'health_check_url' field has been set.
      * URL used for health checking this service
      * @return True if the 'health_check_url' field has been set, false otherwise.
      */
    public boolean hasHealthCheckUrl() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'health_check_url' field.
      * URL used for health checking this service
      * @return This builder.
      */
    public com.tbw.security.securityevents.ServiceStatusChange.Builder clearHealthCheckUrl() {
      health_check_url = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ServiceStatusChange build() {
      try {
        ServiceStatusChange record = new ServiceStatusChange();
        record.service_name = fieldSetFlags()[0] ? this.service_name : (java.lang.String) defaultValue(fields()[0]);
        record.previous_status = fieldSetFlags()[1] ? this.previous_status : (com.tbw.security.securityevents.ServiceStatus) defaultValue(fields()[1]);
        record.current_status = fieldSetFlags()[2] ? this.current_status : (com.tbw.security.securityevents.ServiceStatus) defaultValue(fields()[2]);
        record.status_details = fieldSetFlags()[3] ? this.status_details : (java.lang.String) defaultValue(fields()[3]);
        record.health_check_url = fieldSetFlags()[4] ? this.health_check_url : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ServiceStatusChange>
    WRITER$ = (org.apache.avro.io.DatumWriter<ServiceStatusChange>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ServiceStatusChange>
    READER$ = (org.apache.avro.io.DatumReader<ServiceStatusChange>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.service_name);

    if (this.previous_status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.previous_status.ordinal());
    }

    out.writeEnum(this.current_status.ordinal());

    if (this.status_details == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status_details);
    }

    if (this.health_check_url == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.health_check_url);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.service_name = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.previous_status = null;
      } else {
        this.previous_status = com.tbw.security.securityevents.ServiceStatus.values()[in.readEnum()];
      }

      this.current_status = com.tbw.security.securityevents.ServiceStatus.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.status_details = null;
      } else {
        this.status_details = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.health_check_url = null;
      } else {
        this.health_check_url = in.readString();
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.service_name = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.previous_status = null;
          } else {
            this.previous_status = com.tbw.security.securityevents.ServiceStatus.values()[in.readEnum()];
          }
          break;

        case 2:
          this.current_status = com.tbw.security.securityevents.ServiceStatus.values()[in.readEnum()];
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status_details = null;
          } else {
            this.status_details = in.readString();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.health_check_url = null;
          } else {
            this.health_check_url = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










