/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum ServiceStatus implements org.apache.avro.generic.GenericEnumSymbol<ServiceStatus> {
  STARTING, HEALTHY, DEGRADED, UNHEALTHY, STOPPED, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ServiceStatus\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"STARTING\",\"HEALTHY\",\"DEGRADED\",\"UNHEALTHY\",\"STOPPED\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
