/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum Severity implements org.apache.avro.generic.GenericEnumSymbol<Severity> {
  DEBUG, INFO, WARN, ERROR, CRITICAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Severity\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"DEBUG\",\"INFO\",\"WARN\",\"ERROR\",\"CRITICAL\"],\"default\":\"INFO\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
