/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tbw.security.securityevents;
@org.apache.avro.specific.AvroGenerated
public enum ShutdownReason implements org.apache.avro.generic.GenericEnumSymbol<ShutdownReason> {
  GRACEFUL, FORCED, ERROR, SIGNAL, OUT_OF_MEMORY, EXTERNAL_REQUEST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ShutdownReason\",\"namespace\":\"com.tbw.security.securityevents\",\"symbols\":[\"GRACEFUL\",\"FORCED\",\"ERROR\",\"SIGNAL\",\"OUT_OF_MEMORY\",\"EXTERNAL_REQUEST\"],\"default\":\"GRACEFUL\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
